### PR TITLE
Fix the DefaultArgs rewriter to return the correct sig

### PR DESCRIPTION
**Pull request by che-burashco**
My knowledge of how to normally call the parts of `ast::Send` is a bit limited, since it's my first time touching the core code of Sorbet, so let me know if anything is unclear. Instead of saying changing the fun of send to be `core::Names::returns()` I'm just saying "I've changed the send from `void` to `return`"

### Problem
The `DefaultArgs` rewriter uses two passes:
* in the first pass (https://github.com/sorbet/sorbet/blob/a030e69665f8e58fe9fe00f578dd5008410ae15e/rewriter/DefaultArgs.cc#L43)
  * finds the return value for the param (https://github.com/sorbet/sorbet/blob/a030e69665f8e58fe9fe00f578dd5008410ae15e/rewriter/DefaultArgs.cc#L61)
  * substitutes the `override` send with the `void`.
* in the second pass (https://github.com/sorbet/sorbet/blob/a030e69665f8e58fe9fe00f578dd5008410ae15e/rewriter/DefaultArgs.cc#L85)
  * for return sends the `retType` is moved into the `return` send args
  * for void sends, the send is converted to `return` with an arg of `retType`.
The issue is that when we use `override` there will will be two sends for the return values of the sig after the first pass: either `.void.void` or `.void.return`. as a result when we get to the second `void` the retType is a `nullptr`, so we return an `EmptyTree` (https://github.com/sorbet/sorbet/blob/a030e69665f8e58fe9fe00f578dd5008410ae15e/rewriter/DefaultArgs.cc#L97).

### What changed
I've refactored the code a bit in the second pass to get rid off the switch statement, since the idea is simple: for both void and return sends we want to have a return send with an args equal to `retType`.
As a result I've replaced the logic with:
* changing the `void` send to a `return` send
* adding a deep copy of the retType the send's arg, instead of moving it

### Motivation
This should fix this issue https://github.com/sorbet/sorbet/issues/2229. The problem is that when we have an `override` in the sig the mangled sig that gets returned as a result of the rewriter step is just an emptytree.

### Test plan

See included test

### CODE REVIEW

**Comment by jez** [comment]
Thanks for the PR! I'm a little busy today, but I'll try to find time to review this sometime today or tomorrow.

**Comment by DarkDimius** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HUngCTChvXvv3H

**Comment by DarkDimius** [comment]
http://go/GRhVGjTJ - fixes for stripe

**Comment by che-burashco** [comment]
As I was looking through other PRs, I realized that it's related to this one (should have checked the PR list first 🤦 ): https://github.com/sorbet/sorbet/pull/3187

**Comment by elliottt** [comment]
> As I was looking through other PRs, I realized that it's related to this one (should have checked the PR list first 🤦 ): #3187

I think this fixes the bug that I discovered on: https://github.com/sorbet/sorbet/pull/3187#issuecomment-652177696

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HZIWtbrDqfo72q

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HZIfLvlIK1ly0N

**Comment by che-burashco** [comment]
I merged @krispenney 's commit with an added test case. I think should be g2g now

**Comment by elliottt** [comment]
Thanks! My current plan is to merge this on Tuesday morning.

**Comment by elliottt** [comment]
Stripe migration PR: https://go/pull/247368

**Pull request merged**
