### PR TITLE
add the class method to Kernel

### PR DESCRIPTION
**Pull request by ptarjan**
Somehow this was never in our shims. Pointed out in https://stackoverflow.com/questions/56758793/how-to-call-self-class-from-a-mix-in-module

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
What the heck? Certainly we use `.class` at Stripe, don't we? Why was this never a problem before?

**Comment by ptarjan** [comment]
Maybe they were not in `module`s? I'll go check

**Comment by ptarjan** [comment]
https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20A%0A%20%20def%20foo%0A%20%20%20%20self.class%0A%20%20end%0Aend

**Comment by DarkDimius** [comment]
```
[1] pry(main)> module M
[1] pry(main)*   include Kernel
[1] pry(main)* end
=> M
[2] pry(main)> class S < BasicObject
[2] pry(main)*   include ::M
[2] pry(main)*   def foo
[2] pry(main)*     self.class
[2] pry(main)*   end
[2] pry(main)* end
=> :foo
[3] pry(main)> S.new.foo
=> S
[4] pry(main)> class F < BasicObject
[4] pry(main)*   def foo
[4] pry(main)*     self.class
[4] pry(main)*   end
[4] pry(main)* end
=> :foo
[5] pry(main)> F.new.foo
NoMethodError: undefined method `class' for #<F:0x00007fb2e9a4f828>
from (pry):18:in `foo'
```

**Pull request merged**
