### PR TITLE
fix some Symbol methods signature

### PR DESCRIPTION
**Pull request by giovannibonetti**
This fixes some Symbol methods signature, based on the [equivalent String methods](https://github.com/sorbet/sorbet/blob/master/rbi/core/string.rbi).

### Motivation
Improving accuracy of Sorbet checks.

### Test plan
I haven't found any test for this class yet.

### CODE REVIEW

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HRaxB5b6w46xUN

**Comment by elliottt** [comment]
Could you rebase off of master? The bug that failed your build was fixed yesterday.

**Comment by giovannibonetti** [comment]
> Could you rebase off of master? The bug that failed your build was fixed yesterday.

Done! 👍

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HRn03PVM4ni5UU

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HRn7qDjCDC56KY

**Comment by elliottt** [comment]
Build passing on stripe ci: https://go/builds/bui_HRnSHmYbi8DzDM

**Comment by giovannibonetti** [comment]
Thank you, too! 🙂

**Pull request merged**
