### PR TITLE
Hide `<AttachedClass>` constants from autogen

### PR DESCRIPTION
**Pull request by jez**
### Motivation

This feature caused some problems with our preloader, because it made it look
like certain constants were defined when they actually weren't.

### Test plan

Review by commit to see the test before+after.

### CODE REVIEW

**Comment by froydnj** [comment]
(Alternatively, should we just disable the rewriter pass for `has_attached_class` when running with autogen, like so many other rewriter passes?)

**Comment by jez** [comment]
> (Alternatively, should we just disable the rewriter pass for `has_attached_class` when running with autogen, like so many other rewriter passes?)

While we could do this, I think it's better to let autogen have the full view of the codebase as Sorbet sees it, and let it make decisions about what to include/not include in its exports.

The fact that we have to disable so many errors when running for autogen is because we skip so many rewriter passes, and disabling those errors historically makes it hard to understand why there's a problem (Sorbet was trying to say there's a problem, but we prevented it from saying so).

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_NffV0kVbfuIWwK
→ https://go/builds/bui_NffVKIg5to0oWq

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/buildgroup/bg_Nffk7sDMxiQSdr
→ https://go/builds/bui_NffkhxGcBguAcO

**Pull request merged**
