### PR TITLE
[WIP] Use tagged pointer for TypePtr, reduce/remove virtual dispatch in types

### PR DESCRIPTION
**Pull request by jvilk-stripe**
This PR is super WIP and will be landed as a bunch of smaller changes. The commits in this PR build on each other and are each individually green (at least, in testing locally) which will make it easy to cherry-pick them into smaller PRs later.

Still TODO:
- [x] Inline ClassType (and potentially some other types) into the tagged pointer.
- [x] Remove ProxyType
- [ ] Determine if it is feasible to make BlamedUntyped/etc not use subclassing on ClassType.
  - Possible to set a bit in ClassType and store data in a object to the side?
  - Could steal the `counter` field on TypePtr to point to something...?

### Motivation

Speed. I noticed atomic counter contention on shared class types (e.g., nilClass) is expensive during infer due to cache thrashing. This is a super roundabout way of fixing that problem that also happens to have other benefits (smaller Type objects, faster casting, etc).

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jvilk-stripe** [comment]
I forgot to open as draft. This is not intended for review. :)

**Comment by jez** [comment]
oh wow

**Comment by jvilk-stripe** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_IG7EtmSCSxgjwD

**Comment by jvilk-stripe** [comment]
https://github.com/sorbet/sorbet/pull/3651 covers the last of the changes contained in this WIP PR.

**Pull request closed without merging**
