### PR TITLE
Add missing compact and compact! methods to Hash

### PR DESCRIPTION
**Pull request by jmr0**
### Motivation
Noticed these methods were missing / raising type errors while working on my code.

### Test plan
Wasn't sure how this was done, but happy to look into it.

### CODE REVIEW

**Comment by jez** [comment]
This is going to conflict with #3080 which adds thousands of lines of previously missing RBI definitions, including these two methods.

**Comment by jmr0** [comment]
Thanks @jez - should be all set now.

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HOqoBoMmqby2Xg

**Comment by jez** [comment]
@jmr0 this causes handful of type errors to surface when we tested it on our codebase at Stripe. We'll have to pre-emptively fix those errors before we can accept this PR, so it'll be a little while longer before we can land this.

Thanks for your patience.

**Comment by marianosimone** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HZ18QlMdD3Obp2

**Comment by marianosimone** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HZ36iSRudubGBt

**Comment by marianosimone** [comment]
Thanks for the PR, @jmr0 , and sorry for the delay.

Unfortunately, proper signatures for `Hash#compact` and and `Hash#compact!` are not expressible directly in a Sorbet rbi.

To see this, you can think of the following example:

```ruby
my_hash = T.let({a: 1, b: nil}, T::Hash[Symbol, T.nilable(Integer)])
my_compacted_hash = my_hash.compact
```

Even though you'd expect `my_compacted_hash` to be `T::Array[Symbol, Integer]`, it will still be `T::Array[Symbol, T.nilable(Integer)]` , because the `V` on the proposed signature is indeed `T.nilable(Integer)`.

In these cases, we use c++ implementations instead, as you can see for the case of `Array#compact`:

https://github.com/sorbet/sorbet/blob/343e75f47cd770744456c155e5a3ee6c5130b64d/core/types/calls.cc#L2142-L2158

Feel free to submit another PR doing a similar implementation for `Hash#compact` and/or `Hash#compact` and we’ll be happy to review.

**Pull request closed without merging**
