### PR TITLE
Distinguish final hash literal argument in calls

### PR DESCRIPTION
**Pull request by jez**
### Motivation

The Ruby VM gives special privileges to the last hash literal argument in a
method call. This change more accurately models that.

### Commit summary

- **Refactor to use anonymous namespace** (13365a1da)

  Requires making jumpToDead a private static helper, because otherwise
  the forward declaration doesn't work.

- **Factor out ast::Hash case into buildHash helper** (293ac97a1)

- **Peek at last arg to see if it's a Hash** (0601152ca)

  This change preserves the existing behavior, just to make sure that the
  tests still pass even though I'm peeking one level at last argument.

  This sort of a peek is similar to what the Ruby VM does when it
  commpiles a Ruby program to bytecode. For example:

      ❯ ruby --dump=insns 'foo({x: 12}, {y: 34})'
      == disasm: #<ISeq:<main>@foo.rb:1 (1,0)-(1,19)> (catch: FALSE)
      0000 putself                                                         (   1)[Li]
      0001 duphash                      {:x=>12}
      0003 putobject                    34
      0005 opt_send_without_block       <callinfo!mid:foo, argc:2, kw:[y], FCALL|KWARG>, <callcache>
      0008 leave

  The Ruby VM records the second argument not as a value on the VM stack,
  but with a special operand to the `opt_send_without_block` instruction
  that remembers which explicit keywords were mentioned.

  Which is to say: if the last argument to a method call is a Hash
  literal, it already gets special treatment by the VM, so it's fine for
  us to do the same.

- **Pass magic build hash name in as an argument** (604d32144)

- **Bookkeeping for new <Magic>.<build-keywords-args> Symbol** (91bbb082d)

- **CFGBuilder::buildHash -> walkHash** (e6860ae56)

  Makes grepping for `buildHash` more precise.

- **update testdata exp** (5d1fb9492)

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by trevor-stripe** [comment]
What happens if the method being called takes a hash as the last argument? Will it end up with a special keyword hash instead of an actual hash?

**Comment by jez** [comment]
> What happens if the method being called takes a hash as the last argument? Will it end up with a special keyword hash instead of an actual hash?

Good question, no, this transformation does not change anything with regard to what might happen when the arguments get unpacked.

To convince yourself that this transformation is fine, note that it’s the same transformation that the VM bytecode compiler does, far ahead of having looked up a method entry for the method being called.

The result of this change is just to use an intrinsic with a different name to construct that Hash, so that we can decide to do different things in future changes. In all other respects, `<build-keyword-args>` is the same as `<build-hash>`.

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ file
StandaloneBundle
the
can

config
source
rake
ast
bigdecimal
bundler
byebug
coderay
dogstatsd
excon
multipart-post
interception
jaro_winkler
json
little-plugger
multi_json
method_source
mini_portile2
nio4r
parallel
yard
psych
rack
rainbow
rexml
ruby-progressbar
unicode-display_width
rubyzip
subprocess
tins
faraday
logging
nokogiri
parser
pry
term-ansicolor
terminal-table
sorbet-runtime
pry-byebug
pry-rescue
rubocop
sentry-raven
rubocop-daemon
rubocop-minitest
rubocop-performance
pry-doc
sorbet-runtime
complete!
gems
https://go/builds/bui_Hj5XvxUN4D6XSy

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_Hj5mDUoiBxl3l6

**Pull request merged**
