### PR TITLE
more correctly dedent strings

### PR DESCRIPTION
**Pull request by froydnj**
### Motivation

For the included testcase in this PR, Sorbet was parsing things as:

```
s(:begin,
  s(:class,
    s(:const, nil, :Session), nil,
    s(:begin,
      s(:assign,
        s(:casgn, nil, :MAX_OBJS),
        s(:int, "849201")),
      s(:assign,
        s(:casgn, nil, :MAX_OBJS_MSG),
        s(:dstr,
          s(:str, "There are more than "),
          s(:begin,
            s(:const, nil, :MAX_OBJS)),
          # BUG: we dropped a space here
          s(:str, "objects!  Fire the missiles!
"))))),
  s(:send, nil, :p,
    s(:const,
      s(:const, nil, :Session), :MAX_OBJS_MSG)))
```

This not-quite-correct parsing of heredocs is fine for the static checker, but not so much for the compiler.

This PR cargo-cults the dedent logic from whitequark's parser:

https://github.com/whitequark/parser/blob/b87613d2b99733e1400f076675daf501c19ede93/lib/parser/builders/default.rb#L358-L380
https://github.com/whitequark/parser/blob/b87613d2b99733e1400f076675daf501c19ede93/lib/parser/lexer/dedenter.rb#L36-L79

into our parser.

### Test plan

There's a compiler testcase, which is fine, but every other testcase we have passes, which was surprising to me -- I would have expected some whitequark tests to transition from disabled to enabled.  Or do I have to reimport the upstream parser to add any necessary testcases?  Not really sure what to do here.

cc @vinistock who has worked on this stuff in the past.

### CODE REVIEW

**Comment by froydnj** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_KZ7dZUc37p1dHu
→ https://go/builds/bui_KZ7dw8SQ01XHjM

**Comment by froydnj** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_KZ9qYCQ2HTxY05
→ https://go/builds/bui_KZ9qyCRtaTy1I4

**Comment by froydnj** [comment]
The initial test build linked above were green, but an actual push that tested the compiler failed

I added another compiler testcase and https://go/builds/bui_KZA1UNurKW75Cy should be good.

**Review by aprocter-stripe — APPROVED** [review]
I think I believe that the cargo-culting from the whitequark parser is good, and the test looks good too.

**Pull request merged**
