### PR TITLE
don't crash for non-existent args in the initializer rewriter

### LINKED ISSUE #6383: Crash in rewriter/Initializer.cc
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20A%0A%20%20sig%20%7Bparams%28x%3A%20Integer%2C%20y%3A%20T.nilable%28String%29%29.void%7D%0A%20%20def%20initialize%28x%2C%20y%3Dnil%2C%20%29%0A%20%20%20%20%40x%20%3D%20x%0A%20%20%20%20%40y%20%3D%20y%0A%20%20end%0Aend)

```ruby
# typed: strict

class A
  sig {params(x: Integer, y: T.nilable(String)).void}
  def initialize(x, y=nil, )
    @x = x
    @y = y
  end
end
```

#### Observed output

```
Loading...
```

Crashes at runtime with this backtrace:

```
  * frame #0: 0x00007ff81602f00e libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007ff8160651ff libsystem_pthread.dylib`pthread_kill + 263
    frame #2: 0x00007ff815fb0d24 libsystem_c.dylib`abort + 123
    frame #3: 0x000000010121bfc3 sorbet`abort_message + 195
    frame #4: 0x000000010121b856 sorbet`std::__terminate(void (*)()) + 22
    frame #5: 0x000000010121e18b sorbet`__cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 27
    frame #6: 0x000000010121e105 sorbet`__cxa_throw + 117
    frame #7: 0x00000001011a779d sorbet`void absl::base_internal::(anonymous namespace)::Throw<std::out_of_range>(error=0x00000003093f7c38) at throw_delegate.cc:37:3
    frame #8: 0x00000001011a77f6 sorbet`absl::base_internal::ThrowStdOutOfRange(what_arg="absl::container_internal::raw_hash_map<>::at") at throw_delegate.cc:119:3
    frame #9: 0x0000000100cc1e70 sorbet`decltype(this=0x00000003093f80b0, key=0x00006000002781a8)::ArgKind>::value(std::__1::pair<sorbet::core::NameRef const, sorbet::rewriter::(anonymous namespace)::ArgKind> const* std::__1::addressof<std::__1::pair<sorbet::core::NameRef const, sorbet::rewriter::(anonymous namespace)::ArgKind> const>(std::__1::pair<sorbet::core::NameRef const, sorbet::rewriter::(anonymous namespace)::ArgKind> const&)(decltype(std::__1::__declval<std::__1::pair<sorbet::core::NameRef const, sorbet::rewriter::(anonymous namespace)::ArgKind> const>(0)) std::__1::declval<std::__1::pair<sorbet::core::NameRef const, sorbet::rewriter::(anonymous namespace)::ArgKind> const&>()()))) absl::container_internal::raw_hash_map<absl::container_internal::FlatHashMapPolicy<sorbet::core::NameRef, sorbet::rewriter::(anonymous namespace)::ArgKind>, absl::hash_internal::Hash<sorbet::core::NameRef>, std::__1::equal_to<sorbet::core::NameRef>, std::__1::allocator<std::__1::pair<sorbet::core::NameRef const, sorbet::rewriter::(anonymous namespace)::ArgKind> > >::at<sorbet::core::NameRef, absl::container_internal::FlatHashMapPolicy<sorbet::core::NameRef, sorbet::rewriter::(anonymous namespace)::ArgKind> >(sorbet::core::NameRef const&) const at raw_hash_map.h:156:7
    frame #10: 0x0000000100cbf95e sorbet`sorbet::rewriter::(anonymous namespace)::maybeAddLet(ctx=<unavailable>, expr=0x00006000017281f0, argTypeMap=0x00000003093f8108, argKindMap=0x00000003093f80b0)::ArgKind, absl::hash_internal::Hash<sorbet::core::NameRef>, std::__1::equal_to<sorbet::core::NameRef>, std::__1::allocator<std::__1::pair<sorbet::core::NameRef const, sorbet::rewriter::(anonymous namespace)::ArgKind> > > const&) at Initializer.cc:56:28
    frame #11: 0x0000000100cbe63f sorbet`sorbet::rewriter::Initializer::run(ctx=MutableContext @ 0x00000003093f81a0, methodDef=0x000060000211c000, prevStat=0x0000600002c0c020) at Initializer.cc:206:9
    frame #12: 0x0000000100cf48ec sorbet`sorbet::rewriter::Rewriterer::postTransformClassDef(this=0x00000003093f8388, mdef=0x000060000211c000)::'lambda'(sorbet::ast::MethodDef&)::operator()(sorbet::ast::MethodDef&) const at rewriter.cc:143:45
    frame #13: 0x0000000100cf1573 sorbet`bool sorbet::typecaseHelper<sorbet::ast::ExpressionPtr, sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::MethodDef&)&>(base=0x0000600002c0c028, func=0x00000003093f8388)::'lambda'(sorbet::ast::MethodDef&)&) at typecase.h:77:9
    frame #14: 0x0000000100cf0f93 sorbet`void sorbet::typecase<sorbet::ast::ExpressionPtr, sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::Assign&), sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::Send&), sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::MethodDef&), sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::ExpressionPtr const&)>(base=0x0000600002c0c028, funcs=0x00000003093f83c8, funcs=0x00000003093f8398, funcs=0x00000003093f8388, funcs=0x00000003093f8380)::'lambda'(sorbet::ast::Assign&)&&, sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::Send&)&&, sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::MethodDef&)&&, sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::ExpressionPtr const&)&&) at typecase.h:87:34
    frame #15: 0x0000000100cf0b0d sorbet`sorbet::rewriter::Rewriterer::postTransformClassDef(this=0x00000003093f90f8, ctx=MutableContext @ 0x00000003093f8548, tree=0x0000600002c0c0a0) at rewriter.cc:65:13
    frame #16: 0x0000000100cf07ea sorbet`decltype(self=0x00000003093f90f8, args=0x00000003093f89f0, args=0x0000600002c0c0a0) sorbet::ast::MapFunctions<(sorbet::ast::TreeMapKind)1>::CALL_MEMBER_impl_postTransformClassDef<sorbet::rewriter::Rewriterer, true>::call<sorbet::core::MutableContext&, sorbet::ast::ExpressionPtr&>(sorbet::rewriter::Rewriterer&, sorbet::core::MutableContext&, sorbet::ast::ExpressionPtr&) at treemap.h:168:5
    frame #17: 0x0000000100cef78f sorbet`sorbet::ast::TreeMapper<sorbet::rewriter::Rewriterer, sorbet::core::MutableContext, (sorbet::ast::TreeMapKind)1, (sorbet::ast::TreeMapDepthKind)0>::mapClassDef(this=0x00000003093f8fe8, v=0x0000600002c0c0a0, ctx=MutableContext @ 0x00000003093f89f0) at treemap.h:252:9
    frame #18: 0x0000000100cee78b sorbet`sorbet::ast::TreeMapper<sorbet::rewriter::Rewriterer, sorbet::core::MutableContext, (sorbet::ast::TreeMapKind)1, (sorbet::ast::TreeMapDepthKind)0>::mapIt(this=0x00000003093f8fe8, what=0x0000600002c0c0a0, ctx=MutableContext @ 0x00000003093f8a90) at treemap.h:494:28
    frame #19: 0x0000000100cef754 sorbet`sorbet::ast::TreeMapper<sorbet::rewriter::Rewriterer, sorbet::core::MutableContext, (sorbet::ast::TreeMapKind)1, (sorbet::ast::TreeMapDepthKind)0>::mapClassDef(this=0x00000003093f8fe8, v=0x00000003093f9100, ctx=MutableContext @ 0x00000003093f8eb0) at treemap.h:249:13
    frame #20: 0x0000000100cee78b sorbet`sorbet::ast::TreeMapper<sorbet::rewriter::Rewriterer, sorbet::core::MutableContext, (sorbet::ast::TreeMapKind)1, (sorbet::ast::TreeMapDepthKind)0>::mapIt(this=0x00000003093f8fe8, what=0x00000003093f9100, ctx=MutableContext @ 0x00000003093f8fd8) at treemap.h:494:28
    frame #21: 0x0000000100cee4da sorbet`void sorbet::ast::TreeWalk::apply<sorbet::core::MutableContext, sorbet::rewriter::Rewriterer>(ctx=MutableContext @ 0x00000003093f90e8, func=0x00000003093f90f8, to=0x00000003093f9100) at treemap.h:622:20
    frame #22: 0x0000000100cee27e sorbet`sorbet::rewriter::Rewriter::run(ctx=MutableContext @ 0x00000003093f91d0, tree=(ptr = 0)) at rewriter.cc:208:5
    frame #23: 0x0000000100396873 sorbet`sorbet::realmain::pipeline::runRewriter(gs=0x000000011380ca00, file=(_id = 154), ast=(ptr = 0)) at pipeline.cc:158:12
    frame #24: 0x00000001003974a8 sorbet`sorbet::realmain::pipeline::indexOne(opts=0x00000003093fc788, lgs=0x000000011380ca00, file=(_id = 154), tree=(ptr = 0)) at pipeline.cc:191:20
    frame #25: 0x000000010039c6d0 sorbet`sorbet::realmain::pipeline::index(gs=0x000000011380ca00, files=size=1, opts=0x00000003093fc788, workers=0x0000600002104b40, kvstore=nullptr) at pipeline.cc:644:31
    frame #26: 0x000000010000a012 sorbet`sorbet::realmain::realmain(argc=2, argv=0x00000003093fdd18) at realmain.cc:715:27
    frame #27: 0x0000000100003bc2 sorbet`main(argc=2, argv=0x00000003093fdd18) at main.cc:6:16
    frame #28: 0x000000020534952e dyld`start + 462
```

#### Expected behavior

Should not crash.

- - -

### PR DESCRIPTION
**Pull request by froydnj**
### Motivation

Fixes #6383.

Arguably, this is a problem in the parser, and the `.at()` here is correct.  But I think it would be better to be tolerant of input shaped not quite like we expect.

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
> Arguably, this is a problem in the parser

Thanks, I've opened https://github.com/sorbet/sorbet/issues/6393

**Comment by jez** [comment]
> and the `.at()` here is correct

I don't think this is actually true: this bug reproduces even if the file has no parse errors:

```ruby
# typed: strict

class A
  extend T::Sig

  sig {params(y: T.nilable(String)).void}
  def initialize
    y = 1
    @y = y
  end
end
```

(This would make a good additional test case.)

**Review by jez — APPROVED** [review]
Looks good to me, pending one request to add a test.

**Comment by froydnj** [comment]
> > and the `.at()` here is correct
> 
> I don't think this is actually true: this bug reproduces even if the file has no parse errors:
> 
> ```ruby
> # typed: strict
> 
> class A
>   extend T::Sig
> 
>   sig {params(y: T.nilable(String)).void}
>   def initialize
>     y = 1
>     @y = y
>   end
> end
> ```
> 
> (This would make a good additional test case.)

This is a good catch, added!

**Pull request merged**
