### PR TITLE
Docs: Must run `rbi hidden-definitions`

### PR DESCRIPTION
**Pull request by jaredbeck**
### Motivation

Corrects the command, per [Upgrading a file from ignore to any other sigil](https://sorbet.org/docs/static#upgrading-a-file-from-ignore-to-any-other-sigil)

### Test plan

N/A. Docs.

### CODE REVIEW

**Comment by elliottt** [comment]
@jaredbeck it looks like this failed in CI, as the expectation files aren't matching anymore. Could you update them and rebase this branch off of master?

**Comment by jaredbeck** [comment]
Rebased, and expectation files updated

**Comment by elliottt** [comment]
It looks like some of the snapshot tests need to be updated as well. Could you run:

```
$ tools/scripts/update_exp_files.sh
```

and commit the results?

**Comment by jaredbeck** [comment]
> It looks like some of the snapshot tests need to be updated as well. Could you run:
> 
> ```
> $ tools/scripts/update_exp_files.sh
> ```
> 
> and commit the results?

This command (took 930s!) and then failed with:

```
ERROR: /private/var/tmp/_bazel_jared/1e196076e20525e8f573ea397312bdc9/external/ruby_2_4/BUILD.bazel:5:1: error executing shell command: '/bin/bash -c #!/bin/bash

set -euo pipefail

base="$PWD"
out_dir="$base/bazel-out/host/bin/external/ruby_2_4/toolchain"

declare -a inc_path=()
for path in external/system_ssl_darwin/include bazel-...' failed (Exit 1) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
command ./configure --enable-load-relative --with-destdir=/private/var/tmp/_bazel_jared/1e196076e20525e8f573ea397312bdc9/sandbox/darwin-sandbox/1317/execroot/com_stripe_ruby_typer/bazel-out/host/bin/external/ruby_2_4/toolchain --with-rubyhdrdir=${includedir} --with-rubyarchhdrdir=${includedir}/ruby-arch --disable-install-doc --prefix=/ failed!
checking for ruby... /usr/bin/ruby
config.guess already exists
config.sub already exists
checking build system type... x86_64-apple-darwin19.3.0
checking host system type... x86_64-apple-darwin19.3.0
checking target system type... x86_64-apple-darwin19.3.0
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/var/folders/sb/69c3drbd4pl_0j0xydlssh200000gn/T/tmp.6QXuzmDA':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
build dir: /var/folders/sb/69c3drbd4pl_0j0xydlssh200000gn/T/tmp.6QXuzmDA
ERROR: /Users/jared/git/sorbet/sorbet/gems/sorbet/test/snapshot/BUILD:19:1 error executing shell command: '/bin/bash -c #!/bin/bash

set -euo pipefail

base="$PWD"
out_dir="$base/bazel-out/host/bin/external/ruby_2_4/toolchain"

declare -a inc_path=()
for path in external/system_ssl_darwin/include bazel-...' failed (Exit 1) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 930.278s, Critical Path: 105.07s
INFO: 660 processes: 660 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

Please advise.

**Comment by elliottt** [comment]
Could you look at the `config.log` in `/var/folders/sb/69c3drbd4pl_0j0xydlssh200000gn/T/tmp.6QXuzmDA`? It says that it's unable to run compiled C programs during the check for whether or not ruby is being cross-compiled.

The update script does take quite a while, as it re-runs each test that relies on expectation files to update them with the current output from sorbet. If you'd like quicker iteration time on this one, you can update just the snapshot tests like this:

```
bazel test //gems/sorbet/test/snapshot:update -c opt
```

**Comment by jaredbeck** [comment]
The relevant part of `/var/folders/sb/69c3drbd4pl_0j0xydlssh200000gn/T/tmp.6QXuzmDA/config.log` seems to be:

```
..
configure:4405: checking whether we are cross compiling
configure:4413: /private/var/tmp/_bazel_jared/1e196076e20525e8f573ea397312bdc9/external/llvm_toolchain/bin/cc_wrapper.sh -o conftest   -isystem /private/var/tmp/_bazel_jared/1e196076e20525e8f573ea397312bdc9/sandbox/darwin-sandbox/1317/execroot/com_stripe_ruby_typer/external/system_ssl_darwin/include -isystem /private/var/tmp/_bazel_jared/1e196076e20525e8f573ea397312bdc9/sandbox/darwin-sandbox/1317/execroot/com_stripe_ruby_typer/bazel-out/host/bin/external/system_ssl_darwin/include   -L/private/var/tmp/_bazel_jared/1e196076e20525e8f573ea397312bdc9/sandbox/darwin-sandbox/1317/execroot/com_stripe_ruby_typer/bazel-out/host/bin/_solib_darwin/_U@system_Ussl_Udarwin_S_S_Cssl-import___Uexternal_Ssystem_Ussl_Udarwin_Slib -L/private/var/tmp/_bazel_jared/1e196076e20525e8f573ea397312bdc9/sandbox/darwin-sandbox/1317/execroot/com_stripe_ruby_typer/bazel-out/host/bin/_solib_darwin/_U@system_Ussl_Udarwin_S_S_Ccrypto-import___Uexternal_Ssystem_Ussl_Udarwin_Slib  conftest.c  >&5
conftest.c:10:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
..
configure: exit 1
```

I looked at https://github.com/sorbet/sorbet/blob/master/CONTRIBUTING.md but don't see an relevant instructions there.

Per https://stackoverflow.com/a/5898279/567762, I tried compiling (`cc`) a "hello world" program in C, `using stdio.h` and that worked, so I do have a working complier.

> bazel test //gems/sorbet/test/snapshot:update -c opt

This fails with the same error:

```
checking whether we are cross compiling... configure: error: in `/var/folders/sb/69c3drbd4pl_0j0xydlssh200000gn/T/tmp.IEp3iv5t':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
```

**Comment by elliottt** [comment]
Could you try:

```
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```

This one is referenced from the README.md, rather than CONTRIBUTING.md.

**Comment by jaredbeck** [comment]
> [the instructions are in] the README.md, rather than CONTRIBUTING.md.

Thanks! I followed all the instructions starting with `xcode-select --install`, up to and including `bazel clean --expunge`. The `bazel test` still fails though.

> Could you try:
> 
> ```
> open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
> ```
> 

That file does not exist:

```
ls /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
ls: /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg: No such file or directory
```

I'm re-installing `CommandLineTools` (for a second time) to see if it will provide this `.pkg`, but I'm not hopeful.

This is the hardest I've ever worked to change a few words of documentation 😅 Sorry if it's frustrating for you too.

**Comment by jaredbeck** [comment]
> I'm re-installing `CommandLineTools` (for a second time) to see if it will provide this `.pkg`, but I'm not hopeful.

Re-installing `CommandLineTools` via `xcode-select --install` does not cause this `.pkg` to appear.

I've tried downloading a few older `Command_Line_Tools_*_for_Xcode_*.dmg` from https://download.developer.apple.com but they either do not provide the `.pkg`, or they're too old to be installed on macOS 10.15.

I'm stumped. 

Btw, I **definitely have stdio.h** 

```
find /Library/Developer/CommandLineTools -name 'stdio.h'
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stdio.h
```

**Comment by jaredbeck** [comment]
The absence of the `/Library/Developer/CommandLineTools/Packages` directory on Catalina seems to be a [known issue](https://stackoverflow.com/questions/58278260/cant-compile-a-c-program-on-a-mac-after-upgrading-to-catalina-10-15?noredirect=1&lq=1).

It seems that macOS 10.15 users need to inform `bazel` to look for headers in either:

1. The `CommandLineTools` copy of the SDK: `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include`, or
1. The internal xcode copy of the SDK: `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include`

I've seen suggestions to inform bazel using various env. vars, like `CPATH` or `CFLAGS`. Apparently other compilers heed such vars, but bazel seems to ignore them.

I don't know anything about bazel. How are macOS 10.15 users, supposed to inform bazel of the location of the headers?

**Comment by elliottt** [comment]
I'm not sure how to fix the issues you're seeing with 10.15, so I just fixed the expectation files locally. We're still on 10.14, so once we update I'm sure we'll hit this.

**Comment by jaredbeck** [comment]
Thanks Trevor. I'll let you know if I learn anything more about how to use bazel on macOS 10.15.

**Comment by elliottt** [comment]
@jaredbeck I think the problems you were seeing with Catalina should be fixed with #3062 :)

**Comment by jaredbeck** [comment]
> @jaredbeck I think the problems you were seeing with Catalina should be fixed with #3062 :)

Yeah, seems to be working now. Both of the following worked for me:

```
./bazel build //main:sorbet --config=dbg
tools/scripts/update_exp_files.sh
```

Congratulations, now everyone at Stripe can upgrade to Catalina, right? 😅 Next, ruby 2.7! j/k j/k j/k

**Pull request merged**
