### PR TITLE
Revert "Revert "Speedup lub distribution for big lubs (#3192)""

### PR DESCRIPTION
**Pull request by elliottt**
Reverts sorbet/sorbet#3197

### CODE REVIEW

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HYkE41JScwe2wa

**Comment by elliottt** [comment]
There's an interesting difference in behavior on this branch, cc @DarkDimius.

[sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Adef%20test2(b)%0A%20%20if%20b%20%3D%3D%201%0A%20%20%20%20xs%20%3D%20T%3A%3AArray%5BT.nilable(String)%5D.new%0A%20%20elsif%20b%20%3D%3D%202%0A%20%20%20%20xs%20%3D%20T%3A%3AArray%5BT.untyped%5D.new%0A%20%20end%0A%0A%20%20%23%20On%20the%20lubs%20branch%3A%20T.any(T%3A%3AArray%5BT.nilable(String)%5D%2C%20T%3A%3AArray%5BT.untyped%5D)%0A%20%20%23%20On%20master%3A%20T%3A%3AArray%5BT.untyped%5D%0A%20%20T.reveal_type(T.must(xs))%0A%0A%20%20T.must(xs).each%20%7B%7Cx%7C%20T.reveal_type(x)%7D%20%23%20T.nilable(String)%0Aend%0A)

```ruby
# typed: true

def test2(b)
  if b == 1
    xs = T::Array[T.nilable(String)].new
  elsif b == 2
    xs = T::Array[T.untyped].new
  end

  # On the lubs branch: T.any(T::Array[T.nilable(String)], T::Array[T.untyped])
  # On master: T::Array[T.untyped]
  T.reveal_type(T.must(xs))

  T.must(xs).each {|x| T.reveal_type(x)} # T.nilable(String)
end
```

**Comment by DarkDimius** [comment]
>   T.must(xs).each {|x| T.reveal_type(x)} # T.nilable(String)

is a separate bug/feature request.
We don't do blocks correctly for Or types

**Comment by elliottt** [comment]
I'm going to close this for now. This branch isn't reducing the `T.any` cases in the same way as on master, and migrating that reducing behavior over to the flattened implementation is a little more difficult than I had thought.

**Pull request closed without merging**
