### PR TITLE
Docs: Update CONTRIBUTING.md re: slack

### PR DESCRIPTION
**Pull request by jaredbeck**
This slack does not appear to be open, unless your email address
ends in stripe.com

I'll post a picture on this PR

Screen Shot 2020-12-23 at 19 52 31

### CODE REVIEW

**Comment by elliottt** [comment]
When I open that link in incognito mode, I don't see the `@stripe.com` part of the sign-up. It's definitely not intentional that only Stripe employees be able to use the sorbet-slack -- it's meant for the sorbet open source community to use.

**Comment by jaredbeck** [comment]
> When I open that link in incognito mode, I don't see the `@stripe.com` part of the sign-up.

Did you click on "Create an Account"? Sorry if I'm doing something silly/wrong.

**Comment by elliottt** [comment]
Ah, so this was intentional: we have a different sign-up process that's linked from the website: https://sorbet.org/slack. Would you mind changing your PR to use that link instead, and removing the comment about it being stripe-employee specific?

**Review by elliottt — APPROVED** [review]
Thank you for finding this!

**Pull request merged**
