### PR TITLE
Make fast_big_lubs significantly faster for Mac build.

### PR DESCRIPTION
**Pull request by jvilk-stripe**
Make fast_big_lubs significantly faster for Mac build.

500->300 enums cuts runtime from ~160s -> ~30s on my laptop.

### Motivation

This test timed out on the mac buildbox on master. :( 

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jvilk-stripe** [comment]
Note for context: It's that slow due to debug checks.

**Review by trevor-stripe — APPROVED** [review]
🚢

**Review by elliottt — APPROVED** [review]

**Comment by jez** [comment]
The test was not timing out before #3402. Shouldn't we treat the fact that it is timing out now as evidence that #3402 had the opposite effect?

**Comment by jez** [comment]
> The test was not timing out before #3402. Shouldn't we treat the fact that it is timing out now as evidence that #3402 had the opposite effect?

ah nvm that test was introduced by #3402. I was confusing it with the test for sealed class registration.

**Comment by jez** [comment]
In that case:

Are we still confident that `fast_big_lubs` would fail if introduced before #3402, even given that it's being made smaller?

**Comment by jvilk-stripe** [comment]
> Are we still confident that fast_big_lubs would fail if introduced before #3402, even given that it's being made smaller?

Let me do a perf comparison on my laptop on this version with 300 enums.

* With lub optimization: 33s
* Before lub optimization: I stopped it after 5 minutes.

So, I believe it will fail before #3402

**Pull request merged**
