### PR TITLE
Add sig for method CSV.generate

### PR DESCRIPTION
**Pull request by udn**
Add Sig for Method generate on T.class_of(CSV)

### Motivation
Found error when type checking CSV.generate.

```ruby
string_csv = CSV.generate do |csv|
      csv << [
        'Name',
        'Closed Date',
        'Product Code'
      ]
end
```
```bash
Method generate does not exist on T.class_of(CSV) https://srb.help/7003
    14 |    string_csv = CSV.generate do |csv|
    15 |      csv << [
    16 |        'Name',
    17 |        'Closed Date',
    18 |        'Product Code'
       |...
```

### CODE REVIEW

**Comment by DarkDimius** [comment]
Would your example typecheck under this `sig`?

**Comment by udn** [comment]
> Would your example typecheck under this `sig`?

Do you have a better suggestion for me? Every suggestion will be appreciated.

**Comment by udn** [comment]
I found some error, will be right back for the update.

**Comment by udn** [comment]
Allowed str argument can be empty, String or Hash on method CSV.generate.

method interface : 
CSV.generate( str, **options ) { |csv| ... }
CSV.generate( **options ) { |csv| ... }

working example : 
CSV.generate
CSV.generate("String,String,Number")
CSV.generate(headers: true)

**Pull request closed without merging**
