### PR TITLE
Remove non-stdlib Net:: symbols that conflict with generated RBI

### PR DESCRIPTION
**Pull request by fdr**
This patch renders a lot better with the `git diff --patience` flag,
and you can then pipe it through `| fgrep module` or `| fgrep class`
to see what has been removed.

This avoids having to patch generated Net::SSH gem output all the time
because of conflicts with Sorbet's builtin `stdlib/net.rbi`.  It
defines things that are not part of the stdlib in Ruby, and those
signatures are subject to change by those gems:

    sorbet/rbi/gems/net-ssh@6.1.0.rbi:167: Method Net::SSH::KnownHosts#keys_for redefined without matching argument count. Expected: 1, got: 2 https://srb.help/4010
         167 |  def keys_for(host, options = T.unsafe(nil)); end
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        https://github.com/sorbet/sorbet/tree/8f26c9183e9205508d5f0a9fd93ae4aa335a92da/rbi/stdlib/net.rbi#L8459: Previous definition
        8459 |  def keys_for(host); end
                ^^^^^^^^^^^^^^^^^^

    sorbet/rbi/gems/net-ssh@6.1.0.rbi:176: Method Net::SSH::KnownHosts.search_in redefined without matching argument count. Expected: 2, got: 3 https://srb.help/4010
         176 |    def search_in(files, host, options = T.unsafe(nil)); end
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        https://github.com/sorbet/sorbet/tree/8f26c9183e9205508d5f0a9fd93ae4aa335a92da/rbi/stdlib/net.rbi#L8471: Previous definition
        8471 |  def self.search_in(files, host); end
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### Motivation

Sorbet defines symbols for a gem in the stdlib, and it can conflict with different versions of that gem. 

### Test plan

I don't know by what means this rbi is generated or how such generations get tested, but it seems like people have been patching them by hand as well in the git history.

### CODE REVIEW

**Comment by will** [comment]
This would probably fix my problem https://github.com/sorbet/sorbet/issues/3478 . It's kind of strange for sorbet to include RBI for 3rd party gems in the "stdlib" section. It'd be okay if it was kept up to date though.

hey @brandur help me out and merge this even though you don’t work on sorbet directly

**Comment by elliottt** [comment]
It looks like this was generated by some internal tooling that grouped all of the net related imports into one rbi. I think that probably the right thing to do here is for us to take all the bits that you removed, and put them back in our internal rbi. Thanks for finding this!

**Comment by elliottt** [comment]
Could you run `tools/scripts/update_exp_files.sh` and commit the results?

**Comment by fdr** [comment]
Regrettably not. And, I don't use fedora 27. I use fedora 33. This is Bazel 3.7.0.

```
INFO: Repository llvm_toolchain instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule llvm_toolchain defined at:
  /home/fdr/.cache/bazel/_bazel_fdr/ed02704bb020c19e677ec2dcd8106ff9/external/com_grail_bazel_toolchain/toolchain/rules.bzl:23:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
	File "/home/fdr/.cache/bazel/_bazel_fdr/ed02704bb020c19e677ec2dcd8106ff9/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 87
		_download_llvm_preconfigured(<1 more arguments>)
	File "/home/fdr/.cache/bazel/_bazel_fdr/ed02704bb020c19e677ec2dcd8106ff9/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 102, in _download_llvm_preconfigured
		fail(<1 more arguments>)
Unknown LLVM release: clang+llvm-9.0.0-x86_64-linux-gnu-Fedora27.tar.xz
Please ensure file name is correct.
ERROR: /home/fdr/.cache/bazel/_bazel_fdr/ed02704bb020c19e677ec2dcd8106ff9/external/bazel_tools/src/tools/launcher/BUILD:9:14: @bazel_tools//src/tools/launcher:launcher depends on @llvm_toolchain//:toolchain in repository @llvm_toolchain which failed to fetch. no such package '@llvm_toolchain//': Traceback (most recent call last):
	File "/home/fdr/.cache/bazel/_bazel_fdr/ed02704bb020c19e677ec2dcd8106ff9/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 87
		_download_llvm_preconfigured(<1 more arguments>)
	File "/home/fdr/.cache/bazel/_bazel_fdr/ed02704bb020c19e677ec2dcd8106ff9/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 102, in _download_llvm_preconfigured
		fail(<1 more arguments>)
Unknown LLVM release: clang+llvm-9.0.0-x86_64-linux-gnu-Fedora27.tar.xz
Please ensure file name is correct.
ERROR: Analysis of target '//test/cli:update_autocorrect-private' failed; build aborted: Analysis failed
INFO: Elapsed time: 15.308s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (49 packages loaded, 1061 targets configured)
```

**Comment by elliottt** [comment]
I'll check out your branch and run it tomorrow.

**Comment by fdr** [comment]
> I'll check out your branch and run it tomorrow.

thanks

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_INJ3XkOd07FIGd

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_IULLc3dgaHlEGt

**Review by elliottt — APPROVED** [review]
Thank you for trimming out these definitions!

We should be able to merge this soon -- there was a little bit of work to do to re-generate the dependencies that the stripe codebase was relying on.

The sorbet bump that includes this PR should cherry-pick the commits from https://go/srbi/pull/285682

**Pull request merged**
