### PR TITLE
Revert "Fix splat destructuring type information"

### PR DESCRIPTION
**Pull request by elliottt**
Reverts sorbet/sorbet#2863

I merged this before testing internally: http://go/VhE74Yd0

cc @paracycle

### CODE REVIEW

**Comment by DarkDimius** [comment]
go link not found

**Comment by elliottt** [comment]
> go link not found

Not sure what happened there: http://go/UoOSdvjr

**Comment by elliottt** [comment]
I'm going to hold off on merging this for now, and see how easy it would be to just fix these errors.

**Comment by paracycle** [comment]
For those of us not seeing the go links, can you give an idea of what broke exactly? Did we unearth some broken code or was the original PR doing something it wasn't supposed to?

**Comment by elliottt** [comment]
Yes, sorry for the delay. Here's a minimal reproduction:

```
# typed: strict
a, *b = *T.unsafe([])
```

**Pull request merged**
