### PR TITLE
Add patch to expose need_major_by via GC.latest_gc_info

### PR DESCRIPTION
**Pull request by mirek26**
### Motivation

Adding two patches that enable us to optimize GC and get efficiency savings

1. https://github.com/ruby/ruby/pull/6791 - open, but I hope I'll be able to get some version of this in. This will enable us to get rid of unnecessary minor GCs that we currently run to prevent major GCs during request processing.

    > We trigger GC out-of-band to reduce latency impact on synchronous request processing. It’s not perfect, but it works. One thing we really want to avoid is major GC during request processing - so we don’t want to start request processing in a state where need_major_gc is set. If there is a risk of major GC, we prefer to run it out-of-band, where it doesn't matter for request latency.
    > 
    > Unfortunately, this state is currently not exposed - so we can’t know whether the next GC is set to be major or not. As a workaround, we trigger minor GC twice in a row - if a major GC threshold is hit during the first GC, the second GC is upgraded to major and there is no immediate risk of another major GC. This mostly works, but it's not great and it's not efficient (the second GC is not cheap and it's unnecessary in most cases); this PR makes it possible to do that in a better way by exposing need_major_gc.
    > 
    > It may seem strange to expose it under GC.latest_gc_info but I think it’s a reasonable place because the decision was made during the latest GC.

2. https://github.com/ruby/ruby/pull/4860 - merged long time ago, included in Ruby 3.1. This will remove some unnecessary major GCs due to incorrect calculations

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by mirek26** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_MqmZ0qh4NeIR12
→ https://go/builds/bui_MqmZYG8vnMnKbU

**Comment by mirek26** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_MuCByw0MMuLL3H
→ https://go/builds/bui_MuCBui1hS4idPO

**Comment by mirek26** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_MuCrCVOCJic9ZX
→ https://go/builds/bui_MuCrK4ZwEecEoT

**Review by froydnj — APPROVED** [review]
The patch LGTM.

@mirek26 Is this mergeable in its present state?

**Comment by mirek26** [comment]
@froydnj Yup, should be ready to go!

**Pull request merged**
