### PR TITLE
wip: Correctly model merchant_prop w.r.t. foreign

### PR DESCRIPTION
**Pull request by jez**
### Motivation

The current support for merchant_prop wasn't as good as it could be.

### Commit summary

I recommend reviewing the exp files commit by commit.

- **Add a helper for making constants** (c8faa6a93)

- **Pre-define Opus::Account::Model::Merchant** (3ada7862a)

- **Parse merchant_prop with `foreign:` annotation** (61f3c7a08)

- **tools/scripts/update_testdata_exp.sh test/testdata/rewriter/prop.rb** (297e985e4)

- **Add a test to make sure we error if Merchant is missing** (36921d91c)

- **Add a comment** (5505cfb92)

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
cc @ezra-stripe

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_J3qtK3anBqt0Qp
→ https://go/builds/bui_J3qtpcrTmW7ecC

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_J3sqJVAF9JU2pD
→ https://go/builds/bui_J3sqFYm1XVVCjB

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_J3t4qQS7EnGbID
→ https://go/builds/bui_J3t4bG6evTwsyb

**Review by aprocter-stripe — APPROVED** [review]

**Comment by jez** [comment]
This is going to be too much work to land (1.5k errors)

**Pull request closed without merging**
