### PR TITLE
Add RBI definitions for Bundler

### PR DESCRIPTION
**Pull request by Morriar**
### Motivation

The doc states that 

> Since Ruby 2.6, Bundler is a part of Ruby's standard library.

So let's add the definitions in the payload. 

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HOXAAVCCZbK5ew

**Comment by Morriar** [comment]
@elliottt can you run the tests again on this one please?

**Comment by Morriar** [comment]
@elliottt never mind, I got the status back, thanks.

**Comment by Morriar** [comment]
This one conflicts because signatures already exist for Bundler in `sorbet-typed`.

Since Bundler is now part of stdlib, do you mind if I import the existing signatures here and remove Bundler from `sorbet-typed`?

**Comment by elliottt** [comment]
> This one conflicts because signatures already exist for Bundler in `sorbet-typed`.
> 
> Since Bundler is now part of stdlib, do you mind if I import the existing signatures here and remove Bundler from `sorbet-typed`?

That sounds good to me, thank you!

**Comment by Morriar** [comment]
@elliottt I imported the RBI from `sorbet-typed` added the documentation and updated the expected files.

I also opened a PR to remove it from `sorbet-typed` here: https://github.com/sorbet/sorbet-typed/pull/257 that will need to be merged before this PR can pass the tests.

**Comment by Morriar** [comment]
@elliottt can you unlock the tests again on this one please? Thanks!

**Comment by Morriar** [comment]
Cool, the other error is fixed, now it just needs https://github.com/sorbet/sorbet-typed/pull/257 to be merged.

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HPdFPBtZ8JnXQ0

**Pull request merged**
