### PR TITLE
Optimize `T.must`

### LINKED ISSUE #1101: Improve T.must performance
i'm seeing a 20% hit from `T.must` in some hot code. We've used `T.unsafe` instead, which has negligible impact. A somewhat contrived benchmark example:

```ruby
require 'benchmark'
str = '"qwfpgjluy;arstdhneiozxcvbkm"'

puts Benchmark.measure {
  1000000.times do
    if str.start_with?('"')
      T.must(str[1...-1])
    end
  end
}

puts Benchmark.measure {
  1000000.times do
    if str.start_with?('"')
      str[1...-1]
    end
  end
}

puts Benchmark.measure {
  1000000.times do
    if str.start_with?('"')
      T.unsafe(str[1...-1])
    end
  end
}
```
results in:
```
  0.520000   0.000000   0.520000 (  0.521536)
  0.440000   0.000000   0.440000 (  0.443461)
  0.440000   0.000000   0.440000 (  0.451746)
```
Looking at the [implementation](https://github.com/sorbet/sorbet/blob/069f2c02a1b4663dd902e4092348cd87e849b0ad/gems/sorbet-runtime/lib/types/_types.rb#L180-L195), i would suggest an alternative, with a guard clause for non-falsy values:
```ruby
return arg if arg
# raise if arg is nil
arg
```
This avoids method calls in most invocations (`msg` creation/validation on every `T.must` call also feels like overkill.)

### PR DESCRIPTION
**Pull request by elliottt**
`T.must` checks the type of its optional message argument before testing its first argument for `nil`. This change 

### Motivation
Resolves #1101

### Test plan
See included automated tests.

### CODE REVIEW

**Comment by elliottt** [comment]
> please test it in pay-server first.
> Folks could have overrode `nil?`

This has been tested and deployed in pay-server.

**Comment by elliottt** [comment]
> Do we want to get rid of `msg` too?
> We didn't see much demand for it and I expect it have a cost

I think that's reasonable to do, should we do that in this PR or do that separately?

**Comment by DarkDimius** [comment]
> do that separately?

If something can be done separately without much overhead, better to do it separately!

**Comment by elliottt** [comment]
> > do that separately?
> 
> If something can be done separately without much overhead, better to do it separately!

Sounds good. I'll merge this one in and then rework `T.must` in pay-server to no longer include a message argument.

**Pull request merged**
