### PR TITLE
Stop silencing all call-with-block errors

### LINKED ISSUE #5605: Undefined method, called with a block (proc), is not reported as undefined
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Adef%20foo%28%26b%29%0A%20%20%23%20Should%20report%20%22Method%20undefined_method%20does%20not%20exist%22%0A%20%20undefined_method%28%26b%29%0Aend%0A%0Aprc%20%3D%20-%3E%20%7B%7D%0A%23%20Should%20report%20%22Method%20undefined_method%20does%20not%20exist%22%0Aundefined_method%28%26prc%29)

```ruby
# typed: true
extend T::Sig

def foo(&b)
  # Should report "Method undefined_method does not exist"
  undefined_method(&b)
end

prc = -> {}
# Should report "Method undefined_method does not exist"
undefined_method(&prc)
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

```
editor.rb:6: Method undefined_method does not exist on Object https://srb.help/7003
     6 |  undefined_method
          ^^^^^^^^^^^^^^^^

editor.rb:11: Method undefined_method does not exist on T.class_of(<root>) https://srb.help/7003
    11 |undefined_method
        ^^^^^^^^^^^^^^^^
 
Errors: 2
```

- - -

### PR DESCRIPTION
**Pull request by jez**
### Motivation

Fixes #5605

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_LTJeQwKgbhyiKg
→ https://go/builds/bui_LTJe9Maj5A8MPG

**Review by elliottt — APPROVED** [review]
Looks good! It looks like the same problem exists for [`callWithSplatAndBlock`](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Adef%20foo%28%26blk%29%0A%20%20args%20%3D%20%5B%3Afoo%5D%0A%20%20undefined_method%28*args%2C%20%26blk%29%0Aend). Should we fix that one in a follow-up PR, or would you rather handle it in this one?

**Comment by jez** [comment]
yeah i'll handle it in this one, just wanted to get something up to run test-pr-on-pay-server before running to an interview. i'll also add tests

**Comment by jez** [comment]
> Looks good! It looks like the same problem exists for [`callWithSplatAndBlock`](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Adef%20foo%28%26blk%29%0A%20%20args%20%3D%20%5B%3Afoo%5D%0A%20%20undefined_method%28*args%2C%20%26blk%29%0Aend). Should we fix that one in a follow-up PR, or would you rather handle it in this one?

The callWithBlock and callWithSplatAndBlock share the same implementation, so the fix only has to happen in one place. I've added tests for both cases.

**Pull request merged**
