### PR TITLE
bump `bazel-toolchain` to fix Sonoma linking issues on Mac

### LINKED ISSUE #7528: Unable to build from source on macOS
I've been trying to build Sorbet from source without success. Seems like binaries built by bazel have an `@rpath/libunwind.1.dylib` load command, and that fails to load. 

I've tried using `install_name_tool` to change the load command using the absolute path to the library, but I have to do this over and over again and it's just not feasible 😞 

Here's the error I get 👇 . Note that this happens for other binaries (e.g. `generate_names`, `generate_lsp_messages`, `protoc`,  etc)

```
ERROR: /Users/ruiserra/Rui/code/sorbet/parser/parser/BUILD:85:8: Executing genrule //parser/parser:gen_diagnostics_dclass failed: (Aborted): bash failed: error executing command
  (cd /private/var/tmp/_bazel_ruiserra/248c2fbfd43a0e41373dc3928676b474/execroot/com_stripe_ruby_typer && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/parser/parser/generate_diagnostics dclass > bazel-out/darwin-dbg/bin/parser/parser/include/ruby_parser/diagnostic_class.hh')
# Configuration: 0b849942a1f024370b11b4ec31536c426d3760a771fad16bf596b01ba434c1ed
# Execution platform: @local_config_platform//:host
dyld[40086]: Library not loaded: @rpath/libunwind.1.dylib
  Referenced from: <F74F99F9-A955-3CA1-8D20-FFA4EE34F7B3> /private/var/tmp/_bazel_ruiserra/248c2fbfd43a0e41373dc3928676b474/execroot/com_stripe_ruby_typer/bazel-out/host/bin/parser/parser/generate_diagnostics
  Reason: no LC_RPATH's found
/bin/bash: line 1: 40086 Abort trap: 6           bazel-out/host/bin/parser/parser/generate_diagnostics dclass > bazel-out/darwin-dbg/bin/parser/parser/include/ruby_parser/diagnostic_class.hh
Target //main:sorbet failed to build
```

```sh
otool -l ./bazel-out/host/bin/parser/parser/generate_diagnostics | grep libunwind -A 3 -B 3
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libunwind.1.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 1.0.0
compatibility version 1.0.0
```

`libunwind` is included in the llvm toolchain:

```sh
ls -l ./bazel-sorbet/external/llvm_toolchain_12_0_0/lib/libunwind.*
-rwxr-xr-x  1 ruiserra  wheel  95744 15 Apr  2021 ./bazel-sorbet/external/llvm_toolchain_12_0_0/lib/libunwind.1.0.dylib
lrwxr-xr-x  1 ruiserra  wheel     19  8 Dec 16:22 ./bazel-sorbet/external/llvm_toolchain_12_0_0/lib/libunwind.1.dylib -> libunwind.1.0.dylib
-rw-r--r--  1 ruiserra  wheel  86088 15 Apr  2021 ./bazel-sorbet/external/llvm_toolchain_12_0_0/lib/libunwind.a
lrwxr-xr-x  1 ruiserra  wheel     17  8 Dec 16:22 ./bazel-sorbet/external/llvm_toolchain_12_0_0/lib/libunwind.dylib -> libunwind.1.dylib
```

I don't have `libunwind.dylib` in `/usr/lib` or `/usr/lib/system`.

#### Additional details

```sh
$ sw_vers
ProductName:		macOS
ProductVersion:		14.1.1
BuildVersion:		23B81
```

```sh
$ arch
arm64
````

### PR DESCRIPTION
**Pull request by froydnj**
### Motivation

productivity++

Should really fix #7528

### Test plan

See included automated tests.

### CODE REVIEW

**Review by jez — APPROVED** [review]

**Comment by froydnj** [comment]
Will rebase with https://github.com/sorbet/bazel-toolchain/pull/6 once that merges, since that has an actual explanation of the problem and is more permanent than the commit I used here.

**Comment by Morriar** [comment]
I'm guessing it is to fix the `no LC_RPATH's found` compilation error? If true, I just tried locally and it didn't seem to resolve the issue. Do we need to https://github.com/sorbet/bazel-toolchain/pull/6 to be merged first?

**Comment by froydnj** [comment]
Oh, and d) what version of OS X you are running on and what `/usr/bin/ld -v` says.

**Comment by Morriar** [comment]
Ahh `bazel clean --expunge` did the trick 🎉 

I'm seeing a few warnings:

```
-macosx_version_min has been renamed to -macos_version_min
-macosx_version_min has been renamed to -macos_version_min
ld: warning: ignoring duplicate libraries: '-lm', '-lpthread'
```

But Sorbet does indeed build and no more `no LC_RPATH's found`.

Thanks! ❤️

**Comment by froydnj** [comment]
I changed this to pull in sorbet/bazel-toolchain#7, which reverts sorbet/bazel-toolchain#6 and solves the issue in IMHO a better way.  The new approach is more obviously correct and also more compatible with upstream, should we choose to take that route.

This also builds on Sonoma for me, running tests in `-c dbg` and `--config=buildfarm-sanitized-mac`.

**Pull request merged**
