### PR TITLE
Update File.new signature

### PR DESCRIPTION
**Pull request by ChrisBr**
### Motivation
Updating signatures for `File`. Most of the time Pathname is an accepted type.

### Test plan

See included automated tests.

### CODE REVIEW

**Review by jez — APPROVED** [review]
Thanks!

**Comment by ChrisBr** [comment]
> Thanks!

Super quick, cheers mate 👍

**Comment by jez** [comment]
@ChrisBr i believe CI is failing for you because your merge base is 2+ months old. Can you rebase?

**Comment by ChrisBr** [comment]
@jez updated

**Comment by ChrisBr** [comment]
@jez Anything blocking this?

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_IacTDgSDaGhxAs
→ https://go/builds/bui_IacTwI8M5eMsVe

**Comment by ChrisBr** [comment]
Cheers @jez

**Pull request merged**
