### PR TITLE
Add link to `sorbet` topic on GitHub

### PR DESCRIPTION
**Pull request by jez**
### Motivation

Requested on slack

### Test plan

---

Screen Shot 2019-06-23 at 12 46 53 PM

---

Screen Shot 2019-06-23 at 12 46 43 PM

### CODE REVIEW

**Comment by DarkDimius** [comment]
Are you sure you want to rely on github to choose projects?
I think we may want to have a moderated list of projects that cover different usecases.
WDYT?

**Comment by jez** [comment]
> I think we may want to have a moderated list of projects that cover different usecases.

This is what I want too, but not right now—it's too early. I think that once we have a good selection of projects from the GitHub topic and also from users telling us about their projects, we'll be able to hand-recommend some as good examples.

In the early days, I'm not comfortable "blessing" projects as good examples until we've waited things out a bit.

**Comment by jez** [comment]
For example, I think one thing that we'd be likely to do is have a `hello-sorbet` project that people can easily try out. But in fact, I'd like any project we recommend people to try out to be covered by a test suite and be tested against the latest version of Sorbet (so basically, `hello-sorbet` should be one of our `srb init` snapshot tests).

**Comment by jez** [comment]
:portal-from: DM with Dmitry: we'd like to hold off on this one.

- We want to host the links on sorbet.org, not some other platform like GitHub.
- We want make sure that anything on sorbet.org is high quality, so we'd like to wait a bit to give the community some time to mature.

**Pull request closed without merging**
