### PR TITLE
Fix `undef_method` name in core/module.rbi

### PR DESCRIPTION
**Pull request by Morriar**
### Motivation

Rename `Module#undefMethod` -> `undef_method` and add the corresponding doc.

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by elliottt** [comment]
Internal stripe build: http://go/builds/bui_HLsiNs7DhWj1OQ

**Comment by elliottt** [comment]
@Morriar could you run `tools/scripts/update_exp_files.sh`? It looks like the hidden-method-finder tests and one cli test have differing output. Thanks!

**Comment by Morriar** [comment]
@elliottt fixed, sorry about that!

**Comment by elliottt** [comment]
Thanks!

**Pull request merged**
