### PR TITLE
Move #then/yield_self to Kernel

### PR DESCRIPTION
**Pull request by gustavodegeus**
[This example](https://sorbet.run/?arg=--enable-experimental-requires-ancestor#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20Interface%0A%20%20requires_ancestor%20%7B%20Kernel%20%7D%0A%0A%20%20extend%28T%3A%3AHelpers%29%0A%20%20extend%20T%3A%3ASig%0A%20%20abstract!%0Aend%0A%0Aclass%20MyClass%0A%20%20extend%28T%3A%3ASig%29%0A%20%20include%28Interface%29%0Aend%0A%0Asig%7Breturns%28Interface%29%7D%0Adef%20foo%0A%20%20MyClass.new%0Aend%0A%0Adef%20bar%0A%20%20foo.then%20do%20%7Cstuff%7C%0A%20%20%20%20puts%20stuff.to_s%0A%20%20end%0A%0A%20%20%23It's%20weird%20because%20'tap'%20is%20available%0A%20%20foo.tap%20do%20%7Cstuff%7C%0A%20%20%20%20puts%20stuff.to_s%0A%20%20end%0Aend%0A) should work based on Ruby's spec.
If we have an interface with `requires_ancestor { Kernel }`, we should be able to access `then/yield_self` when working with the interface.

### Motivation
The signature for `#then` and `#yield_self` are in the wrong place. 
It should live within Kernel [based on Ruby's](https://github.com/ruby/ruby/blob/936e54063d4de0e44925e9139cb4d25cce27c187/kernel.rb#L120) spec.

### Test plan

I moved the exiting test to `Kernel` and deleted the `Object` file as it was the only test that was there.

### CODE REVIEW

**Comment by froydnj** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_LnD23XutvavdEd
→ https://go/builds/bui_LnD253o4iiRmXU

**Review by paracycle — COMMENTED** [review]
`itself` and `object_id` also belong in `Kernel` btw:
```ruby
> Object.method(:itself).owner
=> Kernel
> Object.method(:object_id).owner
=> Kernel
```

Moreover:
```
$ ruby -e "p Object.instance_methods(false)"
[]
```
i.e. `Object` has no instance methods defined on itself.

**Comment by gustavodegeus** [comment]
> `itself` and `object_id` also belong in `Kernel` btw:
> 
> ```ruby
> > Object.method(:itself).owner
> => Kernel
> > Object.method(:object_id).owner
> => Kernel
> ```
> 
> Moreover:
> 
> ```
> $ ruby -e "p Object.instance_methods(false)"
> []
> ```
> 
> i.e. `Object` has no instance methods defined on itself.

Cool yeah -  I can open a new PR with these ones.
Thanks for the heads up! 😸

**Comment by gustavodegeus** [comment]
Hey @paracycle , I don't see those methods declared [here](https://github.com/ruby/ruby/blob/936e54063d4de0e44925e9139cb4d25cce27c187/kernel.rb#L120) though. 
Maybe I'm missing something? 🤔

**Comment by froydnj** [comment]
> Hey @paracycle , I don't see those methods declared [here](https://github.com/ruby/ruby/blob/936e54063d4de0e44925e9139cb4d25cce27c187/kernel.rb#L120) though. Maybe I'm missing something? thinking

Those methods are defined in the C source code:

* [`object_id`](https://github.com/ruby/ruby/blob/1177665e6224f8491db82997c8774e9485564e41/gc.c#L14065)
* [`itself`](https://github.com/ruby/ruby/blob/1177665e6224f8491db82997c8774e9485564e41/object.c#L4318)

**Review by froydnj — CHANGES_REQUESTED** [review]
It looks like you need to update the expectation files:

* https://github.com/sorbet/sorbet/blob/master/gems/sorbet/test/hidden-method-finder/thorough/sorbet_ruby_2_7_hidden.rbi.exp
* https://github.com/sorbet/sorbet/blob/master/gems/sorbet/test/hidden-method-finder/thorough/sorbet_ruby_3_0_hidden.rbi.exp
* https://github.com/sorbet/sorbet/blob/master/gems/sorbet/test/hidden-method-finder/simple/sorbet_ruby_2_7_hidden.rbi.exp
* https://github.com/sorbet/sorbet/blob/master/gems/sorbet/test/hidden-method-finder/simple/sorbet_ruby_3_0_hidden.rbi.exp

to remove the definitions for `then` and `yield_self` now that they're defined in the correct place.  (If you do a followup PR to move `itself` and `object_id`, you'd also need to update these files, or you can do it as part of this PR.  Up to you!)

**Comment by gustavodegeus** [comment]
Hey @froydnj , just to make sure I'm trying to do the right thing.

It looks like to generate those filed, all I have to do is to run `gems/sorbet/test/hidden-method-finder/update_hidden_methods_exp.sh`, right?

I'm getting some weird ssl error when I try to do so

```ruby
: > revision.tmp
/usr/bin/ruby --disable=gems ./tool/file2lastrev.rb -q --revision.h --srcdir="." > revision.tmp
./tool/ifchange "--timestamp=.revision.time" "./revision.h" revision.tmp
./revision.h unchanged
# rm -f revision.h
# : > revision.h || : > revision.h
/Library/Developer/CommandLineTools/usr/bin/make -f exts.mk  RUBY="./miniruby -I./lib -I. -I.ext/common " top_srcdir="." note
*** Following extensions are not compiled:
gdbm:
	Could not be configured. It will not be installed.
	Check ext/gdbm/mkmf.log for more details.
openssl:
	Could not be configured. It will not be installed.
	Check ext/openssl/mkmf.log for more details.
*** Fix the problems, then remove these directories and try again if you want.
/Library/Developer/CommandLineTools/usr/bin/make -f enc.mk V="1" UNICODE_HDR_DIR="./enc/unicode/12.1.0" RUBY="./miniruby -I./lib -I. -I.ext/common " MINIRUBY="./miniruby -I./lib -I. -I.ext/common "  enc
```

The entire stack is much bigger but it seems that is all about `openssl`... 🤔 
I tried installing it multiple times but no luck so far.

I'm on Apple M1 fwiw.


Should I just change those files by hand and let CI run again?

**Review by froydnj — APPROVED** [review]
Thank you!

As you have discovered, the story for doing Sorbet development on M1 Macs is not as polished as the x86-64 Mac development experience.  Most things work, but there are some issues around building Ruby and such.

**Comment by gustavodegeus** [comment]
Ah cool, sounds good.

I'm going to put a follow up PR with the `object_id` and `itself` in a bit too.

Thanks for the help with this one. 👍🏼

**Pull request merged**
