### PR TITLE
WIP: What happens if we remove RLE from serialize?

### PR DESCRIPTION
**Pull request by jvilk-stripe**
WIP: What happens if we remove RLE from serialize?

### Motivation

Speed.

### Test plan

Covered by existing tests.

### CODE REVIEW

**Comment by jvilk-stripe** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_IvwtvnCqIQ25Ep
→ https://go/builds/bui_IvwtRUs68O10ZO

**Comment by froydnj** [comment]
Random connection: maybe the way to go is removing RLE *and* being smarter about how we pack integers so we do SIMD decoding.  I'm not sure if this would require us to change the serialization interface so we present more information in one pack/unpack call, or if we buffer things up.

Jeff Dean gave a talk with some ideas:

http://research.google.com/people/jeff/WSDM09-keynote.pdf

And people have expanded on those ideas:

https://lemire.me/blog/2012/09/12/fast-integer-compression-decoding-billions-of-integers-per-second/ + links

**Comment by jvilk-stripe** [comment]
Nice, thanks for the links! My plan was to:

1. See how this (1) impacts the cache size on pay-server and (2) impacts compression performance.
2. If 1 and 2 are acceptable, go to town on making these methods faster.

This will be useful for phase 2.

**Comment by jvilk-stripe** [comment]
Without RLE:

* The size of the compressed global state for Stripe's code grows by ~16%, which is a noticeable bump.
* Serialization time for global state is _~67% slower_. There is a marked change in the amount of time it takes to compress and a slight increase for how long it takes to write large amounts of data (vector resizing overhead?).

Some thoughts:

* We don't preallocate the unpickler vector... but I also don't think we can preallocate it large enough for Stripe's GlobalState object.
* I should run lzbench on payload w/ this change.
* Sorbet should maybe emit a metric for time spent in `Pickler::result` (compression).

**Comment by jvilk-stripe** [comment]
My findings indicate that RLE is totally useful. As Nathan says, it may be good to look into other types of integer packing in the future.

**Pull request closed without merging**
