### PR TITLE
Only pass `-march` flag in linux release builds

### PR DESCRIPTION
**Pull request by jez**
### Motivation

This should hopefully allow Sorbet to work under Rosetta 2 on Apple
Silicon Macs?

It will come as a slight performance degradation (potentially, I haven't
measured) on Intel-based Macs.

### Test plan

Existing tests.

### CODE REVIEW

**Review by froydnj — APPROVED** [review]
I wonder if this has negative effects on the local dev cycle, given that payload compression/decompression is no longer using fancy vector instructions (assuming they use anything from SSE3/SSSE3/SSE4/AVX+).  Probably lost in the noise.

**Comment by jez** [comment]
> I wonder if this has negative effects on the local dev cycle, given that payload compression/decompression is no longer using fancy vector instructions (assuming they use anything from SSE3/SSSE3/SSE4/AVX+). Probably lost in the noise.

Yep, I'm down to measure. But IMO local dev on macOS is already so much slower than Linux I'm not too worried about it.

**Review by connorshea — APPROVED** [review]
These binaries work for me on both my Intel and ARM Mac (through Rosetta 2). No performance penalty on Intel that I can see.

**Comment by nathunsmitty** [comment]
For error tracking purposes: this change fixes #3852

**Comment by jez** [comment]
I've heard three people try this out and say that it works on their Apple Silicon Mac, and also that it doesn't regress performance noticeably.

**Pull request merged**
