### PR TITLE
Find behavior conflicts across threads

### PR DESCRIPTION
**Pull request by ngroman**
Adds a merge step for maps of class to "behavior" loc in `Namer::symbolizeTrees`. This ensures conflicts are found even if they are processed by different workers.

### Motivation
This check was broken if the conflicting defs were processed by different workers.

### Test plan

See included automated tests.

Introduced a conflict in Stripe's codebase and ensured this caught it.

Added timing. The merge ops are fast enough on the codebase that they don't appear in timing data.

### CODE REVIEW

**Comment by ngroman** [comment]
cc @aadi-stripe

**Comment by nroman-stripe** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_LnCwXQM6mjiQBm
→ https://go/builds/bui_LnCwNdOLQfkvyf

**Review by jez — CHANGES_REQUESTED** [review]
Do you mind adding a test?

**Comment by ngroman** [comment]
> Do you mind adding a test?

There's already a test for this in https://github.com/sorbet/sorbet/blob/master/test/cli/conflicting-definition/test.out

But it was passing because the same worker gets both files (I'm guessing this is because there are only two files). I'm not sure what a good way of testing this is given you need to rely on how the workers receive jobs. Do you have any ideas here?

**Comment by jez** [comment]
The number of workers will be `min(cores, numFiles / 2)`

https://github.com/sorbet/sorbet/blob/d1bd0b2c0aa7a943737db6a7f3f7f08a624d5aa9/main/options/options.cc#L834

What do you think about making a CLI test with 10 files, where each file pairwise conflicts with all other files?

**Comment by ngroman** [comment]
This is ready for re-review now.

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_LpVYLkG4TuxsAQ
→ https://go/builds/bui_LpVYUFhzsj0svP

**Comment by jez** [comment]
This looks mostly good to me. My one question is whether creating a map this big makes namer noticeably slower.

**Review by jez — APPROVED** [review]

**Comment by jez** [comment]
I took a look at the performance and there's no noticeable change.

**Pull request merged**
