### PR TITLE
Add missing RBI definitions for RubyVM's AbstractSyntaxTree and Node

### PR DESCRIPTION
**Pull request by Morriar**
### Motivation

Add missing RBI definitions for RubyVM's [AbstractSyntaxTree](https://ruby-doc.org/core-2.6/RubyVM/AbstractSyntaxTree.html) and [Node](https://ruby-doc.org/core-2.6/RubyVM/AbstractSyntaxTree/Node.html).

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by marianosimone** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_I42zcojIijLecB

**Comment by marianosimone** [comment]
Tests in Stripe's codebase were succesful. Letting @jez give the final 👍🏽 , though

**Review by jez — APPROVED** [review]
Thanks!

**Comment by Morriar** [comment]
@jez is anything missing to get this through?

**Pull request merged**
