### PR TITLE
Allow Struct with no args which works today on modern Ruby versions

### PR DESCRIPTION
**Pull request by HParker**
irb(main):001> Struct.new
    => #<Class:0x0000000122927958>

### Motivation

Allow creating `Struct.new` without arguments.

### Test plan

Please advise. I am not sure what is standard practice for testing RBI files.

### CODE REVIEW

**Review by jez — APPROVED** [review]

**Comment by jez** [comment]
thanks!

**Comment by jez** [comment]
you've got some test failures. you should be able to edit or delete some `# error:` comments in the mentioned test that fails to fix the errors.

**Comment by HParker** [comment]
I ran `tools/scripts/update_testdata_exp.sh` like the test output suggested. I don't know how to evaluate the output, so please feel free to advise if the output was wrong or unexpected 🙇‍♂️.

**Review by jez — APPROVED** [review]

**Comment by jez** [comment]
Hey sorry for the delay, I was on vacation for a few weeks.

The new output looks good, it's just saying that certain definitions are on different lines, which makes sense because you deleted a few lines from the file.

(If instead of deleting the `# ^^^ error` lines you had replaced them with empty lines, the snapshot output would not have changed, which is an approach you can consider in the future.)

**Pull request merged**
