### PR TITLE
wip: Intrinsic for `Kernel#nil?`

### LINKED ISSUE #3769: Calling `nil?` on non-nilable value in a conditional doesn't report dead code
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Adef%20main%0A%20%20if%205.nil%3F%0A%20%20%20%20puts%20%22This%20should%20error%20as%20unreachable%22%0A%20%20end%0A%0A%20%20unless%205%0A%20%20%20%20puts%20%22Errors%20as%20unreachable%20as%20expected%22%0A%20%20end%0Aend)

```ruby
# typed: true

def main
  if 5.nil?
    puts "This should error as unreachable"
  end

  unless 5
    puts "Errors as unreachable as expected"
  end
end
```

#### Observed output

```
editor.rb:9: This code is unreachable https://srb.help/7006
     9 |    puts "Errors as unreachable as expected"
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior
I would expect Sorbet to error stating that `puts "This should error as unreachable"` is unreachable (error 7006)

### PR DESCRIPTION
**Pull request by jez**
### Motivation

Fixes #3769

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/pay-server-ruby-typer--bui_LifGZtM3L0WDYL
→ https://go/builds/pay-server-sorbet-check--bui_LifGLYq0Fu7vrh

**Review by froydnj — APPROVED** [review]

**Comment by jez** [comment]
This causes about 700 errors on Stripe's codebase.

I haven't taken much time to figure out whether that's because there's a bug in my implementation, or whether there's actually that many violations that were hidden before.

**Review by vinistock — APPROVED** [review]
🚀

**Comment by froydnj** [comment]
> This causes about 700 errors on Stripe's codebase.

Looking through the first several, they all look like "real" errors in the sense that `nil?` is being called on things that have been statically declared to be non-nilable things.  What's not clear to me is whether those `nil?` calls have been placed there defensively, e.g. props that were declared to be `String` but sometimes (?) are `nil`.

As a sort of gross migration strategy, would we consider doing something like:

1. In the intrinsic, when we are going to return bottom, issue a separate error about calling `nil?` on non-nilable things.
2. Once we have issued that error, return a boolean-typed thing so that we don't get further errors.
3. Silence the error, either by default or solely on Stripe's codebase.
4. Fix the errors at some later point.

Obviously whether (4) happens in any reasonable timeframe is unclear.

This rollout strategy would (assuming we only silenced the errors on Stripe's codebase) at least let non-Stripe Sorbet users benefit from this change.  I think the error might even be clearer than the current error, because we can point out directly that `nil?` is being called on some non-nilable thing, rather than indicating that the entire send produces `FalseClass`, which requires some mental processing to conclude that the receiver is always non-`nil`.

A hand-wavy blue-sky autofix that replaced the send with `true`, combined with some other rubocop-esque mechanism to eliminate useless conditionals (dropping `&& true`, making `... if true` unconditional, etc.), might even be able to automate the process of fixing these errors.

**Comment by jez** [comment]
Closing this for the time being because I don't have time to fix these type errors in the near future, and I can't think of a good way to build autocorrect.

(If you can think of one, please feel free to re-submit another PR with these changes and the autocorrect.)

**Pull request closed without merging**
