### PR TITLE
Only swap if absolutely required

### LINKED ISSUE #5827: Duplicate type in inferred `T.any`
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Afoo%20%3D%20T.let%28nil%2C%20T.nilable%28T%3A%3AHash%5BString%2C%20String%5D%29%29%0A%0Aclass%20Provider%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7Breturns%28T.nilable%28T%3A%3AHash%5BString%2C%20String%5D%29%29%7D%0A%20%20def%20foo%0A%20%20%20%20%7B%7D%0A%20%20end%0Aend%0A%0Aprovider%20%3D%20T.let%28Provider.new%2C%20T.nilable%28Provider%29%29%0Aif%201%20%3D%3D%202%0A%20%20foo%20%3D%20if%201%20%3D%3D%203%0A%20%20%20%20provider%26.foo%0A%20%20else%0A%20%20%20%20T%3A%3AHash%5BString%2C%20String%5D.new%0A%20%20end%0A%20%20T.reveal_type%28foo%29%0Aend)

```ruby
# typed: true

foo = T.let(nil, T.nilable(T::Hash[String, String]))

class Provider
  extend T::Sig
  sig {returns(T.nilable(T::Hash[String, String]))}
  def foo
    {}
  end
end

provider = T.let(Provider.new, T.nilable(Provider))
if 1 == 2
  foo = if 1 == 3
    provider&.foo
  else
    T::Hash[String, String].new
  end
  T.reveal_type(foo)
end
```

#### Observed output

```
Revealed type: T.nilable(T.any(T::Hash[String, String], T::Hash[String, String]))
```

#### Expected behavior

```
Revealed type: T.nilable(T::Hash[String, String])
```

I'd expect sorbet to realize that `T.any(T::Hash[String, String], T::Hash[String, String])` is the same as `T::Hash[String, String]`

### PR DESCRIPTION
**Pull request by jez**
### Motivation

Fixes #5827

Many parts of Sorbet's subtyping depend on using reference equality as a
shortcut for structural equality. When that breaks down, you can get somewhat
weird types like seen in the issue above, where a type is repeated twice.

By more carefully tracking when we can reuse types, we can fix the bug above.

### Test plan

See included automated tests.

### CODE REVIEW

**Review by ilyailya — APPROVED** [review]
LGTM!

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_NRWdPsBYlypIe0
→ https://go/builds/bui_NRWdP4MfQ2Sb5T

**Comment by jez** [comment]
This causes a few tuple type bugs to become more common.

I'm going to see about fixing those bugs before landing this change.

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_NrNQl7obtvsSis
→ https://go/builds/bui_NrNQ2P5D1TSave
→ https://go/builds/bui_NrNQeeIFj9yHTf

**Pull request merged**
