### PR TITLE
Error when giving block to method that doesn't take one

### LINKED ISSUE #4056: Error when passing block to method without `&blk` or `yield`
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Arequire%20'sorbet-runtime'%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20%7Bvoid%7D%0Adef%20foo%0A%20%20puts%20'this%20is%20fine'%0Aend%0A%0Afoo%20%7B%7D%0A%0A%23%20%E2%9D%AF%20ruby%20editor.rb%0A%23%20this%20is%20fine)

```ruby
# typed: strict
require 'sorbet-runtime'

extend T::Sig

sig {void}
def foo
  puts 'this is fine'
end

foo {}

# ❯ ruby editor.rb
# this is fine
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

`foo` does not accept a `&blk` parameter so it cannot `blk.call`, nor does it `yield`.

Thus, it is almost certainly a mistake that a block was given to `foo`. Sorbet should report that error.

- - -

Note: the Ruby VM is technically fine with this code: it does not raise an exception, but we still probably want to do this anyways.

### PR DESCRIPTION
**Pull request by jez**
### Motivation

Fixes #4056

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_J3vhqEUsHeUL6B
→ https://go/builds/bui_J3vhgDTvVV3TRJ

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_J3wKi7GVGEjvpA
→ https://go/builds/bui_J3wKGYrscflQvF

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_J3wa1r1bakxES0
→ https://go/builds/bui_J3wabmXYUt2nFf

**Comment by jez** [comment]
Unique methods:

http://go/gist/jez/a260fab961a851640eac7676617bab71

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_J4PM6gpQmG3DQd
→ https://go/builds/bui_J4PM8uAsIwYkS6

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_J4RVj5a2L4qOp9
→ https://go/builds/bui_J4RVf8NjWP1ZgF

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_J4S4bzhe7FPi6M
→ https://go/builds/bui_J4S4kPqMjIKX38

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_J6BkUYQreULNhI
→ https://go/builds/bui_J6BklGQk9YsvKb

**Comment by jez** [comment]
@aprocter-stripe This is ready for review whenever you get the chance.

**Review by aprocter-stripe — APPROVED** [review]

**Pull request merged**
