### PR TITLE
Don't steal private et al. in namer

### PR DESCRIPTION
**Pull request by jez**
### Motivation

We need to keep `private` and friends in the tree so that we can thread
them all the way through to the flatten after resolver.

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by elliottt** [comment]
Are the errors recorded in the test files just temporary?

**Comment by DarkDimius** [comment]
> Are the errors recorded in the test files just temporary?

these errors are valid errors

**Comment by elliottt** [comment]
> > Are the errors recorded in the test files just temporary?
> 
> these errors are valid errors

https://github.com/sorbet/sorbet/pull/2581/files#diff-90744b7a69292a93ef5fd93418933c27R18

This one is confusing, why is `private` expecting an `Integer`?

**Comment by elliottt** [comment]
> > > Are the errors recorded in the test files just temporary?
> > 
> > 
> > these errors are valid errors
> 
> https://github.com/sorbet/sorbet/pull/2581/files#diff-90744b7a69292a93ef5fd93418933c27R18
> 
> This one is confusing, why is `private` expecting an `Integer`?

Never mind, I read the rest of the test and cleared it up for myself :D

**Comment by jez** [comment]
http://go/builds/bui_GeUKHvnOmfWlam

**Pull request merged**
