### PR TITLE
Make the parser recover from more errors

### PR DESCRIPTION
**Pull request by jez**
### Motivation

We care far more about preserving a method def if it existed before a parse
error was introduced, than about tracking the actual contents of the method
bodies (if we see the same method / class structure, we can take the fast
path).

### Test plan

See included automated tests.

I tested this on pay-server too, but pay-server is a particularly bad test for
this change: every single file / method / line in pay-server currently parses,
and this change only affects files that don't parse. I added some of the tests
that are top-of-mind for me right now, but I'm only so confident that we won't
need to revert this because it doesn't actually give us the fast path results
that we're looking for.

### CODE REVIEW

**Comment by DarkDimius** [comment]
@jez a test failed

**Comment by jez** [comment]
@DarkDimius chatted with nroman and he said that the autogen classlist failure is harmless.

**Comment by jvilk-stripe** [comment]
I am very excited about this change.

If I understand it correctly, it's:

1. Reporting the same parse error.
2. Not throwing away the rest of the nodes.

...right? And it doesn't cause issues with things like `x.\nend` because this isn't a hack that changes what is/is not parseable?

**Comment by jez** [comment]
> If I understand it correctly, it's:

I'd say it's more like "now the parser is able to recover from errors even when there isn't a full `stmt` following the parse error".

**Comment by jez** [comment]
But yes, this doesn't change the grammar, so it reports the same errors.

**Pull request merged**
