### PR TITLE
Allow defaultArgs to be checked for override methods

### PR DESCRIPTION
**Pull request by krispenney**
fixes https://github.com/sorbet/sorbet/issues/3161

In the DefaultArgs rewriter, `overrides` are translated to voids.
However, this causes issues are there are both a `params` and
`override` (void) in the same signature.

https://github.com/sorbet/sorbet/blob/576e1fe628309d57783b13d7d7c7e7c546060b49/rewriter/DefaultArgs.cc#L74-L78

When params are hit, the retType is moved into the send's args. When
the override is later hit, the retType is now nil (because of the
move), this means that an empty tree is returned from `mangleSig`. This
causes the sig for the override not to be written.

https://github.com/sorbet/sorbet/blob/576e1fe628309d57783b13d7d7c7e7c546060b49/rewriter/DefaultArgs.cc#L87-L102

As the signature isn't written, this causes the defaultArg to return
`T.untyped`. Then later in inference, anything compared to untyped
will pass, hiding the error.

image

This changes the move to a deepCopy, allowing the return value to be used later on.

### Motivation

As default arguments are not checked against the signatures for abstract/interface implementations, it would be easy for errors to be introduced by not conforming to the interface. This is also a deviation from how default args are treated in regular methods.

### Test plan

See included automated tests. I added an additional test for this scenario.

### CODE REVIEW

**Comment by elliottt** [comment]
Thanks for catching this!

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HS9PwMG8ljYplg

**Comment by elliottt** [comment]
This will require a little bit of work on stripe's codebase to land, so I'll take it from here. Thanks!

**Comment by krispenney** [comment]
Cool, thanks so much!

**Comment by che-burashco** [comment]
Hey guys, sorry, I just realized that my [PR](https://github.com/sorbet/sorbet/pull/3201) that I was originally putting for https://github.com/sorbet/sorbet/issues/2229 is actually related to this one. Should have suggested the changes her instead of opening a separate PR 🤦 . Let me know how you guys would like to proceed

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HX7bUdBLHLaFv3

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HZ1Dx4zFtGZw1Y

**Comment by elliottt** [comment]
@krispenney I found another example that doesn't work, do you mind if I push a fix to this branch?

If `override` has arguments given, then appending to the argument list will produce a call to returns with too many arguments.

```ruby
# typed: true

class A
  extend T::Sig

  sig {params(x: T::Hash[T.untyped, T.untyped]).returns(Integer)}
  def test(x: {})
    10
  end
end

class B < A
  sig {override(allow_incompatible: true).params(x: T::Hash[T.untyped, T.untyped]).returns(Integer)}
  def test(x: {})
    10
  end
end
```

**Comment by krispenney** [comment]
@elliottt Oh nice catch! I didn’t realize `override` accepted arguments. And sure, feel free to add the commit here.

**Comment by elliottt** [comment]
@krispenney it looks like #3201 already fixes the bug that I discovered, do you mind if we close this PR in favor of that one?

**Comment by che-burashco** [comment]
Does it make sense to add the tests that Kris added to #3201 ?

**Comment by elliottt** [comment]
> Does it make sense to add the tests that Kris added to #3201 ?

I won't turn down more tests 👍

**Comment by krispenney** [comment]
No worries, I'll close out this one

**Pull request closed without merging**
