### PR TITLE
Small T::Props API simplifications

### PR DESCRIPTION
**Pull request by djudd-stripe**
Two changes:
1. Remove `mutate_prop_backdoor!`
2. Remove the `strict` option from `deserialize`/`from_hash`

### Motivation
A smaller API is nicer where we can get away with it, but more specifically:
1. This was always a hack, and it's not used in pay-server anymore
2. Strict deserialization is ~buggy in that strictness doesn't propagate recursively to deserializing subdocs. Since the `strict` parameter for serialization _does_ propagate recursively, there's a misleading false parallelism. This change removes that, enabled by https://git.corp.stripe.com/stripe-internal/pay-server/pull/200014

### Test plan
Primarily, a passing pay-server build

There was no test coverage here so I added very basic tests

### CODE REVIEW

**Comment by djudd-stripe** [comment]
Marking wip to clarify this shouldn't be merged because there's still an open pay-server PR. Should be reviewable, though.

**Comment by djudd-stripe** [comment]
pay-server is now prepped: https://cibot.corp.stripe.com/builds/bui_GYNFTOasxVJU5M

**Comment by DarkDimius** [comment]
Hi David, I'm happy to approve it, let me know if you'd like to get it merged or if you want an additional pair for eyes from storage side.

**Comment by djudd-stripe** [comment]
I think this can be merged as-is. I cleared the idea with KV Client folks in advance.

**Pull request merged**
