### PR TITLE
Bail out of constant "Did you mean" suggestions

### PR DESCRIPTION
**Pull request by jez**
### Motivation

Very frequently, "Did you mean" suggestions are the most expensive part of type
checking, because there are hundreds or thousands of missing constant errors,
and the global state search space is huge.

These suggestions are still useful, but they have diminishing returns to
reporting them. This implements a local check when we loop over all the
constants to stub to see if we should skip the check or not.

### Test plan

Review by commit to see the test diff before and after the fix.

### CODE REVIEW

**Comment by paracycle** [comment]
This will be super handy, however, I wonder if adding a global flag to suppress did-you-mean output completely would also be helpful. So far, when working on the Shopify codebase, the errors that are raised have mostly been from a strictness level problem or a missing dependency and did-you-mean errors had very little use for us. It would be good to be able to disable them completely via a CLI flag.

It looks like the flag addition on top of this PR would mostly be adding the flag and supplying its value as the default value of `suggestDidYouMean`.

**Comment by Morriar** [comment]
I wonder if we could avoid disabling it by using a [BKTree](https://www.geeksforgeeks.org/bk-tree-introduction-implementation/) for the search?

**Comment by jez** [comment]
I was kind of hoping to avoid adding more booleans to globalstate and more flags for people to know about, and this seemed like a good way to achieve that. In your case, it would report “did you mean” errors only for the first few results, and the cut off. So if you’re having lots of missing constant errors because or RBIs and stuff, it seems like this will still help out. I’d say in general we prefer not having to add config flags unless there’s a material improvement, because it means there are fewer codepaths to test, fewer things to have missing documentation, etc.

**Comment by jez** [comment]
As far as changing the data structure, we could do that, but as @paracycle mentions, frequently the constant actually isn’t defined in sorbet, so nothing would help. So since did you mean suggestions are so/so on value, I’d rather not sink a ton of time into it

**Comment by Morriar** [comment]
Related to #1293, if we expect people parsing the output themselves, an option `--no-did-you-mean` would be quite helpful for them.

**Pull request merged**
