### PR TITLE
Prohibit calls on T.class_of, fix T.class_of in generics

### LINKED ISSUE #3985: T.class_of with generics seems to make an untyped generic
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0AT.reveal_type(T%3A%3AArray%5BT.class_of(Integer)%5D.new)%0A%0AT.reveal_type(T%3A%3ASet%5BT.class_of(Integer)%5D.new))

```ruby
# typed: true

T.reveal_type(T::Array[T.class_of(Integer)].new)

T.reveal_type(T::Set[T.class_of(Integer)].new)
```

#### Observed output

```
editor.rb:3: Revealed type: T::Array[T.untyped] https://srb.help/7014
     3 |T.reveal_type(T::Array[T.class_of(Integer)].new)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got T::Array[T.untyped] originating from:
    editor.rb:3:
     3 |T.reveal_type(T::Array[T.class_of(Integer)].new)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

editor.rb:5: Revealed type: T::Set[T.untyped] https://srb.help/7014
     5 |T.reveal_type(T::Set[T.class_of(Integer)].new)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got T::Set[T.untyped] originating from:
    editor.rb:5:
     5 |T.reveal_type(T::Set[T.class_of(Integer)].new)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 2
```

#### Expected behavior

Output should show

```
T::Array[T.class_of(Integer)]
T::Set[T.class_of(Integer)]
```

for the revealed types, but they're both `T.untyped` now.

- - -

There should probably be an intrinsic for `T.class_of` in `calls.cc` that makes this method return a `MetaType`.

This is going to be super similar to the code in #3425, as well as #3426 / #3428.

https://github.com/sorbet/sorbet/pull/3425/files#diff-717a663f2a73fc1bdb6cd11c379e821ed258871b4f623a550b755f1998b392c7R16-R20

### LINKED ISSUE #4257: Prohibit T.class_of as a value
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0AT.class_of(Integer).foo)

```ruby
# typed: true
T.class_of(Integer).foo
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

There should be an error, like there is on other runtime types:

```ruby
# typed: true
T.untyped.foo
```
[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0AT.untyped.foo)

```
editor.rb:2: Call to method foo on T.untyped mistakes a type for a value https://srb.help/7030
     2 |T.untyped.foo
        ^^^^^^^^^^^^^

editor.rb:2: Method foo does not exist on Object component of <Type: T.untyped> https://srb.help/7003
     2 |T.untyped.foo
        ^^^^^^^^^^^^^
  Got <Type: T.untyped> originating from:
    editor.rb:2:
     2 |T.untyped.foo
        ^^^^^^^^^
Errors: 2
```

- - -

Similar to https://github.com/sorbet/sorbet/issues/3428, see the linked PRs for suggested implementations.

### LINKED ISSUE #4258: Prohibit T.self_type as a value
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0AT.self_type.foo)

```ruby
# typed: true
T.self_type.foo
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

There should be an error, like there is on other runtime types:

```ruby
# typed: true
T.untyped.foo
```
[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0AT.untyped.foo)

```
editor.rb:2: Call to method foo on T.untyped mistakes a type for a value https://srb.help/7030
     2 |T.untyped.foo
        ^^^^^^^^^^^^^

editor.rb:2: Method foo does not exist on Object component of <Type: T.untyped> https://srb.help/7003
     2 |T.untyped.foo
        ^^^^^^^^^^^^^
  Got <Type: T.untyped> originating from:
    editor.rb:2:
     2 |T.untyped.foo
        ^^^^^^^^^
Errors: 2
```

- - -

Similar to https://github.com/sorbet/sorbet/issues/3428, see the linked PRs for suggested implementations.

### PR DESCRIPTION
**Pull request by jez**
### Motivation

Fixes #4257
Fixes #3985

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_JqBAYoD3Gg9pjz
→ https://go/builds/bui_JqBABiWVL3vXtv

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_JqBSXO0qVDT59E
→ https://go/builds/bui_JqBSWns4EHqkqZ

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_JqD2vmkOkiWbN2
→ https://go/builds/bui_JqD2mhmUvhuE3q

**Review by aprocter-stripe — APPROVED** [review]
All makes sense to me!

**Pull request merged**
