### PR TITLE
Disable checking each element in an `Enumerable`

### PR DESCRIPTION
**Pull request by jafc-stripe**
Enumerables are not neccessarily finite, so checking each value within
can cause infinite loops at runtime.

For example, the following code does not terminate.

```ruby
T.let([42].cycle, Enumerable[Integer])
```

This PR disables exaustively iterating over an enumerator and checking
the type of each element.

### Motivation

https://github.com/sorbet/sorbet/issues/1792

### Test plan

I've added a test for exactly this case.

### CODE REVIEW

**Comment by DarkDimius** [comment]
Jake is away

**Comment by rafaelfranca** [comment]
Should we disable only in the case the Enumerator is infinity? We should be able to know:

```
>> x=["bad"].cycle
=> #<Enumerator: ["bad"]:cycle>
>> x.size
=> Infinity
```

**Comment by jafc-stripe** [comment]
@rafaelfranca that solves this case, but my main reason for fixing this is that adding types to a file caused an enumerator that wrapped an expensive computation (passed in by a caller outside of our team) to cause a module to consistently time out.

Because walking an Enumerator can execute arbitrary code, adding typing to a file can change it's behavior pretty dramatically. I think not forcing _any_ enumerators makes adding Sorbet less likely to cause problems when it's adopted into previously untyped code.

**Comment by rafaelfranca** [comment]
Yeah, good point about some enumerator being expensive. You could have an enumerator that does access external services and you don't want to make those access just to check if the return type is from the type you defined. I think this is a nice compromise, and behaves in the same way as `Lazy`.

Speaking on that should we remove the special check for `Lazy` now that both `Enumarator` have the same behavior?

**Comment by jafc-stripe** [comment]
@rafaelfranca ooh good catch!

**Comment by DarkDimius** [comment]
@jafc-stripe is this the state you want to get this is?
If so, happy to approve & merge

**Comment by jez** [comment]
@jafc-stripe I removed the redundant code that @rafaelfranca pointed out. I'm going to merge this when the tests pass.

**Pull request merged**
