### PR TITLE
RBI commands should respect ignores in configuration

### PR DESCRIPTION
**Pull request by wpride**
### Motivation
`srb rbi gems` and `srb rbi hidden-definitions` currently do not respect files ignored in `sorbet/config` as `srb tc` does. This can cause major problems when these steps require all files. For example, requiring [`db/schema.rb`](https://edgeguides.rubyonrails.org/active_record_migrations.html) will wipe out the entire database. This file is auto-generated so adding `typed: ignore` to the top is not possible.

### Test plan
I did not add a test for this because I couldn't find any existing `rspec` tests to model off of/add to and am not in a position to set this up. I ran both commands across our code base. 

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
For one thing, it sounds like we should blacklist requiring `db/schema.rb`. We already do this for other files.

**Comment by wpride** [comment]
@jez That would be great and solve the primary case I'm worried about here

**Comment by elliottt** [comment]
I think we'd like to approach adding this functionality from a different angle, as the behavior you're encoding already exists in the sorbet executable. I've added #1340 with a short write up of an approach that @jez and I discussed if you're interested in working through that change.

Separately, I'll add `db/schema.rb` to the list of files that we ignore, to avoid wiping your database :)

**Comment by wpride** [comment]
@elliottt That makes complete sense, thanks (and thank you for the blacklist addition). I'd love to take a crack at this - could you point me towards where `sorbet -p file-table-json` is called currently in `srb`? I couldn't find it grepping

**Comment by elliottt** [comment]
It's not currently called in `require_everything.rb`, but I think you would need to pass the [`abs_paths`](https://github.com/sorbet/sorbet/blob/889e1bf69bf55e093929cbc427334fb864f7b077/gems/sorbet/lib/require_everything.rb#L46) array to the sorbet executable, along with `-p file-table-json --stop-after=parser`. You could then parse the json output from sorbet, rather than iterate over the files produced by the glob.

**Comment by wpride** [comment]
Closing in favor of https://github.com/sorbet/sorbet/pull/1351

**Pull request closed without merging**
