### PR TITLE
Try to add mergify

### PR DESCRIPTION
**Pull request by ptarjan**
I was looking for a MergeBot replacement and all directions seemed to point at this thing. What do you folks think about trying it?

We have some decisions to make?
- Should it just auto-merge or should we have to add a label or something for it to merge? (I have it requiring the `mergify` label)
- Should we delete the head branch after merge? (I don't have that now)
- Do we want to require all requested reviews to be approved (I don't have that now)

Here are some examples to help inspire you: https://doc.mergify.io/examples.html#examples

### Test plan
```
curl -F 'data=@.mergify.yml' https://gh.mergify.io/validate
The configuration is valid
```

### CODE REVIEW

**Comment by jez** [comment]
@ptarjan I don't think this thing actually is related to MergeBot at all. It seems like it's just something that automatically merges. I don't think it does anything to re-run the tests against the latest master on an integration branch, does it?

**Comment by ptarjan** [comment]
@jez nope, it doesn't do that part. But it will land PRs for you once the tests pass, so that part is there.

**Comment by ptarjan** [comment]
They do have a "strict workflow" that tries to solve that problem: https://doc.mergify.io/strict-workflow.html#the-strict-workflow-solution . I would vote we try that as a second phase if we want.

**Comment by jez** [comment]
In that case, I'd like it to be opt-in. Can we set a rule that says "the PR must have a `mergify-submit` label on it"?

**Comment by DarkDimius** [comment]
https://doc.mergify.io/strict-workflow.html suggests they do have mergebot-like thing

**Comment by DarkDimius** [comment]
I'm suggesting strict rebase as described in 
https://medium.com/mergify/new-rebase-method-with-strict-mode-15c40961029d

**Comment by DarkDimius** [comment]
/me slowpoke, Paul already posted the same link :-)

**Comment by ptarjan** [comment]
Ok. We can just straight to that. Do you still want it opt in @jez?

**Comment by jez** [comment]
@ptarjan yeah i kind of still want it opt in. I kind of don't want to have to remember to tag the PRs that are approved + passing tests but pending a pay-server codemod.

**Comment by jez** [comment]
I worry that it would have the opposite effect, that I'd just start only using `comment` until the tests pass.

**Comment by ptarjan** [comment]
ok, I'll disagree and commit. strict and opt-in with the label "mergify"

**Comment by DarkDimius** [comment]
Note: this will stretch our mac CI even more thin before @aisamanra finishes work on adding linux ruby build.
I'm onboard but don't want this to come as a surprise.

**Comment by ptarjan** [comment]
@DarkDimius I think that's fine. We are still able to stop testing everything on mac on non-master right? I'd rather do that than not have mergebot.

**Comment by DarkDimius** [comment]
Yes, I'm onboard.

**Comment by ptarjan** [comment]
Is anyone willing to approve this?

**Pull request merged**
