### PR TITLE
Revert "Forbid `return <expr>` when returning `void` (#1355)"

### PR DESCRIPTION
**Pull request by jez**
This reverts commit 1ef624a315b68e3ca51fcb0e5bed2038862f510a.

### Motivation

We didn't test this enough, and it's incorrectly making errors when it
shouldn't.

### CODE REVIEW

**Comment by DarkDimius** [comment]
Could you illustrate a case where it was wrong?

**Comment by jez** [comment]
> Could you illustrate a case where it was wrong?

From IRL: it doesn't handle the distinction between blocks and procs.

**Comment by jez** [comment]
Also there's just a lot of things we don't fully understand about the Ruby VM here.

**Comment by jez** [comment]
```
@x = nil
def foo(&blk)
  @x = blk.to_proc
  # @x = lambda do
  #   puts 1
  # end
  # @x = lambda do
  #   blk.call
  # end
end

def bar
  foo do
    return 1
  end
end

p bar

def qux
  @x.call
end

p qux
```

note to future me: we were trying to make sense of this example

**Comment by azdavis** [comment]
More context: This impl depended on the supposed fact that, if you see a `return expr` inside a method def, then that `return` is returning out of the method. This is not true, because of procs and lambdas and blocks and things.

Additionally, we think that it is not statically knowable in general whether a return inside a block-looking thing will return from the enclosing method or return from the block itself.

**Comment by XrXr** [comment]
Here's a diabolical example to show that it's not statically knowable:
```ruby
def sometimes_transform(&b)
  if rand > 0.5
    o = Object.new
    o.define_singleton_method(:block, &b)
    o.block
  else
    b.call
  end
end

def who_knows
  sometimes_transform { return :inner }
  :outer
end

puts who_knows
```
The return inside the block sometimes returns who_knows, sometimes doesn't.

**Pull request merged**
