### PR TITLE
Add Instacart to who is using sorbet section on sorbet.org

### PR DESCRIPTION
**Pull request by singhai0**
Thanks for building Sorbet – we use it extensively here at Instacart for our new Ruby projects.

### Motivation
Popularize?

### Test plan
N/A; unsure if there's something testing the asset pipelines for the website.

### CODE REVIEW

**Comment by jez** [comment]
Thanks! Can you use a square logo?

**Review by jez — CHANGES_REQUESTED** [review]
^

**Comment by singhai0** [comment]
Done. Thanks @jez.

**Review by jez — APPROVED** [review]

**Comment by jez** [comment]
Thanks! When the branch passes, it will merge to master and the website will automatically publish.

**Pull request merged**
