### PR TITLE
WIP: Preallocate Symbol and Name tables during index.

### PR DESCRIPTION
**Pull request by jvilk-stripe**
Preallocate Symbol and Name tables during index.

In a multi-core environment, preallocating all of these tables to their maximal sizes imposes memory overhead that increases with the number of cores.

This change resizes the name and symbol tables only during the procedure that merges symbol and name tables together which should substantially reduce memory consumption on many core machines but may increase per-core runtime slightly due to resizing.

### Motivation

Reduce max RSS.

### Test plan

N/A

### CODE REVIEW

**Comment by DarkDimius** [comment]
nice!

**Comment by jvilk-stripe** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_IULEGaIyqIXnZx

**Comment by jvilk-stripe** [comment]
This change didn't have the impact I expected.

First off, this change does not have any impact on warm cache typechecking memory consumption because we preallocate to the nearest power of 2 when deserializing GlobalState out of the cache, which happens prior to indexing. We have to do this for the name table for correctness (due to how namesByHash works), but we don't have to do this for the symbol table. In fact, resizing the symbol table to the nearest power of two is new behavior that I introduced when I split up the symbol table, and may be the root cause of the resulting memory increase! I'll test that hypothesis next. 

This change seems to have ~5% impact on the memory consumption of cold cache typechecking, which is less than I expected.

**Comment by jvilk-stripe** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_IUMXDLO633IMb4

**Comment by jvilk-stripe** [comment]
Well, dang. None of this had any impact. I must be missing something. Closing for now.

**Pull request closed without merging**
