### PR TITLE
Add support for optional `random` argument to `Array#sample`

### PR DESCRIPTION
**Pull request by olivierbellone**
See https://ruby-doc.org/core-2.6.5/Array.html#method-i-sample

### Motivation
RBI fix.

### Test plan
See included automated tests.

### CODE REVIEW

**Comment by olivierbellone** [comment]
Updated with more signatures to support all overloads.

ptal @jez

**Comment by ptarjan** [comment]
It looks like you have test failures

**Comment by olivierbellone** [comment]
@ptarjan Could you provide some guidance here?

`Array#sample` can return two different types depending on whether `arg0` is passed:
- without `arg0`, it returns a single (nilable) `Elem`
- with `arg0`, it returns a `T::Array[Elem]`

Both invocations can also accept an optional `random` keyword argument that does not change the return type.

I've tried a few different things but they all fail with:
> Malformed `sig`. Overloaded functions cannot have keyword arguments:  `random` https://srb.help/5003

Is this a Sorbet limitation?

**Comment by ptarjan** [comment]
Yeah, that sounds like a limitation of Sorbet that we can't do signatures like that. You can try to work through that if you want but I'm not sure why it was added. Maybe blame the code that throws that error and see why it was added?

If you can't change Sorbet on that, then I think you have a decision to make. Do you want the overloaded behavior or do you want the keyword arg?

**Comment by olivierbellone** [comment]
AFAICT this check was added by @DarkDimius in this commit: https://github.com/sorbet/sorbet/commit/643ee2fd17c439f96b3531dbaa54d55d88fbc117#diff-58b7d14280a0e081f7abb766c8a3d21bR522

If it's not possible to lift this limitation, I guess I could define a single signature like so:

```ruby
  sig do
    params(
        arg0: Integer,
        random: Random,
    )
    .returns(T.any(T.nilable(Elem), T::Array[Elem]))
  end
  def sample(arg0=T.unsafe(nil), random: T.unsafe(nil)); end
```

This seems to work, but it's kind of a bummer since we no longer know which type is returned depending on which parameters are passed.

**Comment by ptarjan** [comment]
@olivierbellone well, your suggestion seems like a net win so feel free to update to that if you'd like it

**Comment by olivierbellone** [comment]
@ptarjan Updated, ptal.

**Comment by ptarjan** [comment]
I asked @DarkDimius and the limitation for kwargs in overloaded functions if because you can call a function with a hash and it populates the kwargs and we don't know which overload to choose

**Comment by olivierbellone** [comment]
@ptarjan That makes sense. Do you think we can release this PR in its current state?

**Comment by ptarjan** [comment]
I think so but I'll hand it off to @gdritter-stripe as he is oncall this week

**Comment by aisamanra** [comment]
This type change causes a few dozen errors on our codebase (because things that were previously known to be `A` might now become `T.any(A, T::Array[A])` instead) and I want to fix those before I merge this, but this is on my stack and I'll merge it soon.

**Comment by olivierbellone** [comment]
@aisamanra Gentle bump :)

**Pull request merged**
