### PR TITLE
Add RBI definition for `Enumerable#zip`

### PR DESCRIPTION
**Pull request by Morriar**
### Motivation

Missing RBI for `Enumerable#zip`.

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by Morriar** [comment]
Note that I reused the same RBI definition than [`Array#zip`](https://github.com/sorbet/sorbet/blob/master/rbi/core/array.rbi#L2274-L2280) which does not define `block`.

**Comment by DarkDimius** [comment]
```
[1] pry(main)> [1].zip([1]) do
[1] pry(main)*   1
[1] pry(main)* end
=> nil
```
it seems that if you give a block, it doesn't return zipped array. Could you update signature to indicate this?

**Comment by ptarjan** [comment]
@Morriar Are you going to be able to take a look at this? If not, please close.

**Comment by Morriar** [comment]
I will, at some point.

Feel free to close, I can reopen later.

**Pull request closed without merging**
