### PR TITLE
Allow sharing NameRefs between siblings when name is in common ancestor

### LINKED ISSUE #1076: --cache-dir ENFORCE: NameRef not owned by correct GlobalState
#### Input

- `mkdir cache` make an empty dir for cache
- `echo "class A; end" >> a.rb` 
- `touch {b,c,d}` extra empty files to trick Sorbet into parallel mode
- `sorbetdev a.rb {b,c,d} --cache-dir cache` 
-  `echo '# just a comment' >> a.rb` 
- `sorbetdev a.rb {b,c,d} --cache-dir cache` rerun after modification

#### Observed output

This happens on `--config=dbg` and `--config=release-debug-mac` as of 650f254c3bd8d4a3a9d3c5045db09abc764e49b7

```
👋 Hey there! Heads up that this is not a release build of sorbet.
Release builds are faster and more well-supported by the Sorbet team.
Check out the README to learn how to build Sorbet in release mode.
To forcibly silence this error, either pass --silence-dev-message,
or set SORBET_SILENCE_DEV_MESSAGE=1 in your shell environment.

Exception::raise(): core/Names.cc:196 enforced condition false has failed: NameRef not owned by correct GlobalState

Backtrace:
sorbet::core::NameRefDebugCheck::check(sorbet::core::GlobalState const&, int) const (in libcore.so) + 352
void sorbet::core::DebugOnlyCheck<sorbet::core::NameRefDebugCheck, true>::runDebugOnlyCheck<sorbet::core::GlobalState const&, int>(sorbet::core::GlobalState const&&&, int&&) const (in libcore.so) + 68
sorbet::core::NameRef::enforceCorrectGlobalState(sorbet::core::GlobalState const&) const (in libcore.so) + 63
sorbet::core::NameRef::data(sorbet::core::GlobalState&) const (in libcore.so) + 565
sorbet::core::GlobalState::enterClassSymbol(sorbet::core::Loc, sorbet::core::SymbolRef, sorbet::core::NameRef) (in libcore.so) + 366
sorbet::namer::NameInserter::squashNames(sorbet::core::MutableContext, sorbet::core::SymbolRef, std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >&) (in libnamer.so) + 2357
sorbet::namer::NameInserter::preTransformClassDef(sorbet::core::MutableContext, std::__1::unique_ptr<sorbet::ast::ClassDef, std::__1::default_delete<sorbet::ast::ClassDef> >) (in libnamer.so) + 770
sorbet::ast::PostPonePreTransform_ClassDef<sorbet::namer::NameInserter, sorbet::core::MutableContext, true>::call(sorbet::core::MutableContext, std::__1::unique_ptr<sorbet::ast::ClassDef, std::__1::default_delete<sorbet::ast::ClassDef> >, sorbet::namer::NameInserter&) (in libnamer.so) + 100
sorbet::ast::TreeMapper<sorbet::namer::NameInserter, sorbet::core::MutableContext>::mapClassDef(std::__1::unique_ptr<sorbet::ast::ClassDef, std::__1::default_delete<sorbet::ast::ClassDef> >, sorbet::core::MutableContext) (in libnamer.so) + 146
sorbet::ast::TreeMapper<sorbet::namer::NameInserter, sorbet::core::MutableContext>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::MutableContext) (in libnamer.so) + 2123
std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> > sorbet::ast::TreeMap::apply<sorbet::core::MutableContext, sorbet::namer::NameInserter>(sorbet::core::MutableContext, sorbet::namer::NameInserter&, std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >) (in libnamer.so) + 165
sorbet::namer::Namer::run(sorbet::core::MutableContext, sorbet::ast::ParsedFile) (in libnamer.so) + 115
sorbet::realmain::pipeline::name(sorbet::core::GlobalState&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, bool) (in libpipeline.so) + 1217
sorbet::realmain::pipeline::resolve(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&, bool) (in libpipeline.so) + 160
sorbet::realmain::realmain(int, char**) (in librealmain.so) + 7553
main (in sorbetdev) (main.cc:7)
start (in libdyld.dylib) + 1
0x00000007 (in sorbet)

a.rb:1: Failed to process tree (backtrace is above) https://srb.help/1001
     1 |class A; end
        ^^^^^^^^^^^^
fish: 'sorbetdev a.rb {b,c,d} --cache-…' terminated by signal SIGSEGV (Address boundary error)
```

#### Expected behavior

No errors. Is the ENFORCE overly strict here? I don't have enough context to know what's happening. Maybe the tree loaded from cache doesn't have the right global state id?

### PR DESCRIPTION
**Pull request by XrXr**
### Motivation
Names in the initial global state have stable ids across all children.

When we load a GS from cache, it could have extra names that are not well
known. We could then process inputs that solely reference those names and
trigger substitution fast path as our trees do not add new names. Since no
substiution happens to our tree, cross GS name use can happen later. Our debug
checks wasn't accounting for this case.

### Test plan

See included automated tests.

Fix #1076

### CODE REVIEW

**Comment by DarkDimius** [comment]
The loop just below the code that you added does, what I believe to be a correct transformation of handling common ancestor chain of global state:
https://github.com/sorbet/sorbet/blob/master/core/Names.cc#L191-L195

**Comment by XrXr** [comment]
> under proposed patch the code will believe that name tables in gs3 and gs4 are the same.

The changes here makes it so that the first 1000 names that were in gs0 are usable in `gs{1,2,3,4}`. Why would `gs3` and `gs4` be treated the same? Names above 1000 are checked  the same way they were before this change. This does assume that the size of the name table increase monotonically, though.

> The loop just below the code that you added does, what I believe to be a correct transformation of handling common ancestor chain of global state:

The code doesn't solve the problem of sibling trees referencing names loaded from cache, which is why the attached test case fails on master. When the gs is loaded from cache, `A` is already in the name table before we process any input. When the indexing step sees `A`, it inserts no new names. 

When we merge goes together at the end of indexing, no substitution happens because no new names were inserted. The `NameRef`s in the tree now reference a GS we throw away after merging it into the one we return -- a sibling GS of the GS that makes it to namer. So, while the code handles NameRefs that reference GSs that were parent, it doesn't help us here. (the name references a sibling instead of any parent)

**Comment by DarkDimius** [comment]
> The changes here makes it so that the first 1000 names that were in gs0 are usable in gs{0,1,2,3,4}. Why would gs3 and gs4 be treated the same? Names above 1000 are checked the same way they were before this change. This does assume that the size of the name table increases monotonically, though.

Because as `gs3` is result of deepCopy on `gs1` it has `rootGlobalStateNamesUsed` set to `2000`, which is the same value as `gs4` will use despite having different set of names in 1000-2000 range.
This will allow a name from `gs3` in `1000-2000` range to be looked up in `gs4` without triggering an assert.

> In general this check is similar to the LAST_WELL_KNOWN_NAME check above. names present in the initial GS loaded from cache effectively become well known since they are inherited by all children.

There is a huge difference between the two. There is a compile-time guarantee that _all_ global states share the same names in `0-LAST_WELL_KNOWN_NAME` range, while the proposed sequence of actions in comment above proves that the check introduced in this PR wrongly believes to be safe.

> When we merge together GSs at the end of indexing, no substitution happens because no new names were inserted. The NameRefs in the tree now reference a GS we threw away after merging it into the one we return -- a sibling GS of the GS that makes it to namer. So, while the loop handles NameRefs that reference GSs that were parent, it doesn't help us here. (the name A references a sibling GS instead of any parent)

I agree that the current check might not be covering _all_ cases that are safe. At the same time, it's crucial for us to not introduce checks that cover _any_ cases that are unsafe, like the one described above. Concurrency bugs are some of the hardest bugs to debug and we'll be super conservative in checks around concurrency.

**Comment by XrXr** [comment]
> Because as gs3 is result of deepCopy on gs1 it has rootGlobalStateNamesUsed set to 2000, which is the same value as gs4 will use despite having different set of names in 1000-2000 range.

`rootGlobalStateNamesUsed` is set only once, when the GS is unpickled from the a payload, be it from the kvstore or from the baked payload. This means gs0-4 all have `rootGlobalStateNamesUsed` as 1000. I will write a test to prove this.

**Comment by DarkDimius** [comment]
> rootGlobalStateNamesUsed is set only once, when the GS is unpickled from the a payload, be it from the kvstore or from the baked payload. This means gs0-4 all have rootGlobalStateNamesUsed as 1000. I will write a test to prove this.

serialization is a wrong abstraction to base from, as you currently rely on that no new names are inserted into the very original GlobalState before `deepCopy`. This assumption isn't necessarily true and can be easily violated by inserting a name that will be used in one of files, triggering the same ENFORCE.

I think we need a better scheme than this one, let me think for a couple of days.


Another question is: I wonder why are you running into this problem when Stripe doesn't? How are you using Sorbet differently from us?

**Comment by DarkDimius** [comment]
One potential idea(in debug move) to have every name ref store not the GlobalStateId that it happened to be created it(commonly the most recent one), but a globalStateId from the GlobalState that has first introduced this name.

E.g. in a scheme

```
auto gs1 = createInitialGlobalState(...); // lets say this has globalStateId == 0
gs1->enterNameUtf8("demo");
auto gs2 = gs1->deepCopy(); // lets say this has globalStateID == 1
auto nameRef = gs2->enterNameUTF8("demo"); // this currently has globalStateID == 1 in name ref, if it had 0, the _existing_ check would permit it, right?
```

**Comment by XrXr** [comment]
> serialization is a wrong abstraction to base from, as you currently rely on that no new names are inserted into the very original GlobalState before deepCopy.

Yes. Instead of setting it when de-serializing maybe a better place to put it would be `payload::createInitialGlobalState`, but yes, it relies on no new names being inserted between when `rootGlobalStateNamesUsed` is set and `deepCopy` happens.

> One potential idea(in debug move) to have every name ref store not the GlobalStateId that it happened to be created it(commonly the most recent one), but a globalStateId from the GlobalState that has first introduced this name.

This sounds more robust than what I have here and doesn't suffer from the problem of relying on setting `rootGlobalStateNamesUsed` at the right time :)

> I wonder why are you running into this problem when Stripe doesn't?

I ran into this while writing tests #1136. I suppose I could simply tweak the test so that I evade this ENFORCE by forcing a substitution... Might still be worthwhile to relax the check to facilitate future testing, though.

**Comment by DarkDimius** [comment]
> I ran into this while writing tests #1136. I suppose I could simply tweak the test so that I evade this ENFORCE by forcing a substitution... Might still be worthwhile to relax the check to facilitate future testing, though.


Makes sense, this seems like indeed a case where we should make ENFORCE permit this safe usage. Let's fix it properly!

> This sounds more robust than what I have here and doesn't suffer from the problem of relying on setting rootGlobalStateNamesUsed at the right time :)

Do you want to take a stab a this? :-)

**Comment by XrXr** [comment]
Ok, tried in 1b1a983

**Comment by DarkDimius** [comment]
Awesome, this seems much better to me: it reuses existing mechanism rather than rolling a new one.

I've kicked off CI. I'd like to quickly confirm that it doesn't introduce a huge slowdown in debug builds. After doing so, we'll merge!

**Pull request merged**
