### PR TITLE
Format one-line sig blocks in an autocorrect suggestion with spaces inside the curly braces.

### LINKED ISSUE #7258: Include spaces inside curly brackets in abstract method autocorrect
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20MyAbstractClass%0A%20%20extend%20T%3A%3ASig%2C%20T%3A%3AHelpers%0A%20%20abstract!%0A%0A%20%20sig%20%7B%20abstract.void%20%7D%0A%20%20def%20example%3B%20end%0Aend%0A%0Aclass%20MyClass%20%3C%20MyAbstractClass%0Aend%0A)

```ruby
# typed: true

class MyAbstractClass
  extend T::Sig, T::Helpers
  abstract!

  sig { abstract.void }
  def example; end
end

class MyClass < MyAbstractClass
end

```

#### Observed output

```
editor.rb:11: Missing definition for abstract method `MyAbstractClass#example` https://srb.help/5023
    11 |class MyClass < MyAbstractClass
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:8: example defined here
     8 |  def example; end
          ^^^^^^^^^^^
  Autocorrect: Use -a to autocorrect
    editor.rb:12: Insert sig {override.void}
      def example; end
    12 |end
        ^
Errors: 1
```

#### Expected behavior

The most common Ruby style guides suggest putting braces inside curly brace blocks. Our autocorrect should so that too.

- - -

### PR DESCRIPTION
**Pull request by lerebear**
### Motivation

Closes #7258.

This changes the formatting of sig blocks in an autocorrect suggestion from e.g. `sig {override.void}` to `sig { override.void }`. This conforms with the style most commonly adopted in the Ruby community.

### Test plan

See included automated tests.

### CODE REVIEW

**Review by jez — APPROVED** [review]

**Comment by jez** [comment]
You have a few more test failures, mostly because this codepath also affects how `hover` requests present the method definition. I think it's fine to have the new formatting in all places, but some more tests will need to change.

**Comment by lerebear** [comment]
I will address the test failures shortly 👍🏿 .

That said, @jez do you have a recommendation for how to run all tests locally so that I can get ahead of test failures like the ones observed in CI?

I tried `bazel test test --config=dbg`, but that didn't seem to target all of the necessary tests. Conversely `bazel test //... --config=dbg` doesn't work for me locally (even after a `bazel clean`): I get multiple errors that look like this:

```sh
ERROR: file 'main/lsp/_objs/lsp_preprocessor_test/lsp_preprocessor_test.pic.o' is generated by these conflicting actions
```

**Comment by jez** [comment]
The three test suites that are most likely to fail:

- PosTests
- LSPTests
- cli tests

You can run these with

```
bazel test --config=dbg --test_summary=terse //test:test_corpus_lsp //test:test //test/cli:cli
```

**Comment by lerebear** [comment]
I believe that tests on this branch should now pass 🤞🏿

**Review by froydnj — APPROVED** [review]

**Pull request merged**
