### PR TITLE
Add T::Enum.each_values

### PR DESCRIPTION
**Pull request by djudd-stripe**
### Motivation
https://github.com/sorbet/sorbet/issues/2671

Similar to the reporter's motivation there, I'd like to enable Style/HashEachMethods in pay-server at some point, and this will make it easier.

### Test plan
Typechecks

### CODE REVIEW

**Review by trevor-stripe — CHANGES_REQUESTED** [review]
This seems good to me. Would you mind adding a test to `gems/sorbet-runtime/test/types/enum.rb`?

**Comment by djudd-stripe** [comment]
Added a test and that caught a bug, whoops! Thanks for the suggestion.

**Review by elliottt — APPROVED** [review]

**Comment by jez** [comment]
This is going to have problems if you're using it in practice because of the `T.any`, right? Sorbet will mistakenly force you to consider the case that you have a T::Enumerator. Can we make two methods? One that takes a block and one that doesn't? that way they can have separate types.

**Comment by elliottt** [comment]
> This is going to have problems if you're using it in practice because of the `T.any`, right? Sorbet will mistakenly force you to consider the case that you have a T::Enumerator. Can we make two methods? One that takes a block and one that doesn't? that way they can have separate types.

You're totally right. We avoid this in the stdlib by using overloading, which we don't allow elsewhere. I'll revert this.

**Comment by djudd-stripe** [comment]
I think the two methods solution doesn't work because we need to match the `Hash#each_values` API - that's the whole point.

Could we do this if we just set the return type to `T.untyped`? A hack but not sure there's a better option while we can't use overloading.

**Pull request merged**
