### PR TITLE
Adds type parameters to Kernel#Array

### PR DESCRIPTION
**Pull request by kbacha**
The types were being erased by the signature when sorbet is actually
smart enough to infer the correct types. This may cause new type checks
to fail but should be correct.

### Motivation

We were using `Array(x)` to collapse an input which was `T.any(String, T::Array[String])` into just an array of strings. However, it was erasing the type to `T::Array[T.untyped]`.

I was able to create a prototype [here](https://sorbet.run/#%23%20typed%3A%20strict%0A%0A%23%20your%20example%0AT.reveal_type%28T.let%28Array%28%22a%22%29%2C%20T%3A%3AArray%5BInteger%5D%29%29%0A%0A%23%20the%20kernel%20method%0AT.reveal_type%28Array%28%22a%22%29%29%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20type_parameters%28%3Ain%29.params%28args%3A%20T.type_parameter%28%3Ain%29%29.returns%28T%3A%3AArray%5BT.type_parameter%28%3Ain%29%5D%29%0Aend%0Adef%20array%28*args%29%0A%20%20args%20%0Aend%0A%0A%23%20my%20parameterized%20value%0AT.reveal_type%28array%28%22a%22%29%29%0A%0A%23%20Let%20validation%0AT.let%28array%28%22a%22%29%2C%20T%3A%3AArray%5BInteger%5D%29%0AT.let%28array%28%22a%22%29%2C%20T%3A%3AArray%5BString%5D%29%0AT.let%28array%28%22a%22%2C%20123%29%2C%20T%3A%3AArray%5BT.untyped%5D%29%0AT.reveal_type%28array%28%22a%22%2C%20123%29%29).

### Test plan

Not sure how to test this but @jez said he would help out.

### CODE REVIEW

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_LRmn7xvuQhTha5
→ https://go/builds/bui_LRmnOrHKCQU9Sz

**Comment by jez** [comment]
This causes about 100 new type errors on Stripe's codebase.

It looks like some of those errors are because the types added in this PR are wrong:

```ruby
Array('a'..'z')
```

should have type `T::Array[String]` but this PR makes it think that the type is `T::Array[T::Range[String]]`.

Some of the errors do look like type errors that should be reported, though. It will take some time to silence those on Stripe's codebase, which i might not have time for today. You can go ahead and try to fix the range example above and I'll re-test with the new PR to see how many of the errors it fixes.

**Comment by jez** [comment]
Another one:

```ruby
Array([0])
```

should have type `T::Array[Integer]` but after this PR it has type `T::Array[T::Array[Integer]]`

**Comment by kbacha** [comment]
@jez Ok, played with the example a bit more and I changed the logic to contain another signature. This time one that matches on `T::Enumerable` and maps the type member to the return type.

I think that this works even if I don't use the splat but I'm not positive. I'm also not positive about precedence when matching signatures.

Here's the [playground link](https://sorbet.run/#%23%20typed%3A%20strict%0A%0A%23%20your%20example%0AT.reveal_type%28T.let%28Array%28%22a%22%29%2C%20T%3A%3AArray%5BInteger%5D%29%29%0A%0A%23%20the%20kernel%20method%0AT.reveal_type%28Array%28%22a%22%29%29%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20type_parameters%28%3Ain%29.params%28args%3A%20T.type_parameter%28%3Ain%29%29.returns%28T%3A%3AArray%5BT.type_parameter%28%3Ain%29%5D%29%0Aend%0Adef%20array%28*args%29%0A%20%20args%20%0Aend%0A%0A%0Asig%20do%0A%20%20type_parameters%28%3Ain%29.params%28args%3A%20T%3A%3AEnumerable%5BT.type_parameter%28%3Ain%29%5D%29.returns%28T%3A%3AArray%5BT.type_parameter%28%3Ain%29%5D%29%0Aend%0Adef%20array2%28args%29%0A%20%20args.to_a%0Aend%0A%0A%23%20my%20parameterized%20value%0AT.reveal_type%28array%28%22a%22%29%29%0A%0A%23%20Let%20validation%0AT.let%28array%28%22a%22%29%2C%20T%3A%3AArray%5BInteger%5D%29%0AT.let%28array%28%22a%22%29%2C%20T%3A%3AArray%5BString%5D%29%0AT.let%28array%28%22a%22%2C%20123%29%2C%20T%3A%3AArray%5BT.untyped%5D%29%0AT.reveal_type%28array%28%22a%22%2C%20123%29%29%0AT.reveal_type%28array2%28%22a%22..%22z%22%29%29)

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_LRoB4tGFmxoerC
→ https://go/builds/bui_LRoBzoD2cmL4AQ

**Comment by jez** [comment]
Some more test cases

```ruby
Array(nil)

x = T.let('', T.any(String, T::Array[String])
Array(x)

y = T.let('', String)
Array(y)
```

Most of the errors on Stripe's codebase after this change point to this PR being buggy, mostly with the above test cases.

**Comment by jez** [comment]
Heads up that you can write tests for this change by creating the file `test/testdata/rbi/kernel_array.rb` and running

```
./bazel test //test:test_PosTests/testdata/rbi/kernel_array
```

In the test file, you can use `# error:` assertions to state what the content of the error messages should be and where they should be raised. see the README.md for more information.

**Comment by jez** [comment]
I believe your current changes treat this:

```ruby
maybe_x = T.let(nil, T.nilable(String))
res = Array(maybe_x)
T.reveal_type(res)
```

as revealing a type of `T::Array[T.nilable(String)]`, but the correct type should be `T::Array[String]`.

Sorbet will only select one overload. It will not attempt to break down the `T.any(NilClass, String)` type into parts, treat it as a call to `Array()` at `NilClass` or to `Array()` at `String`, and merge the results.

**Comment by kbacha** [comment]
@jez That's true, but wouldn't `T::Array[T.nilable(String)]` still be more specific that `T::Array[T.untyped]`?

**Comment by jez** [comment]
> @jez That's true, but wouldn't `T::Array[T.nilable(String)]` still be more specific that `T::Array[T.untyped]`?

We err on the side of convenient than strict in cases where we try to model the standard library, because people are annoyed when Sorbet does not let them use things that they know for sure that the standard library in fact lets them do.

Again, we welcome people to make their own type-safe wrappers around standard library methods that they use in their own projects.

**Comment by kbacha** [comment]
@jez Well, crazy as it sounds, if the Enumerable comes first and we provide the NilClass case, we can make that work too.

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_LSx7ayl0DfnmYi
→ https://go/builds/bui_LSx75WaqwLvwWr

**Comment by jez** [comment]
The most recent changes take it down to just 4 type errors on Stripe's codebase. that's very reasonable, thank for working through all those edits. i'll land the fixes for those today, then i'll be able to merge this pr

**Review by jez — APPROVED** [review]

**Pull request merged**
