### PR TITLE
Error statically when foreign is not a lambda

### PR DESCRIPTION
**Pull request by jez**
### Motivation

Follow up to #2682 from @jerry-stripe

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
Marking `wip` until Stripe's codebase is fixed.

**Comment by DarkDimius** [comment]
@jez @jerry-stripe what's the state of this PR?

**Comment by jerry-stripe** [comment]
I believe pay-server has been bumped up so this should be safe to proceed with: https://git.corp.stripe.com/stripe-internal/pay-server/pull/212187

**Comment by jez** [comment]
I'm going to rebase and test this over pay-server

**Comment by jez** [comment]
http://go/builds/bui_Gq1J7RUVNTLDPl

**Pull request merged**
