### PR TITLE
wip: Implement intrinsics for [] and []= on shape types

### PR DESCRIPTION
**Pull request by jez**
SEO: square brackets index square_brackets squareBrackets squareBracketsEq eq

### Motivation

This should help ease the pain of #3822.

Right now I've implemented it stacked on top, but we might want to land them in
the opposite order, or at the same time.

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_Ibs0EnWGUF9tJX
→ https://go/builds/bui_Ibs0MPuuS6D5JC

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_Ibsp7eRrmQwBtQ
→ https://go/builds/bui_IbsqSkaRpZbdKt

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_IbsuzN5y7tIB67
→ https://go/builds/bui_IbsulFkmdiWaFd

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_Ibt0FddeLcnAn2
→ https://go/builds/bui_Ibt0qMn99xieXX

**Comment by karmakaze** [comment]
This would be amazing to land on its own, as I've begun working on a specific subset in #4497 that could be very useful in combination.

**Comment by jez** [comment]
As cool as this change is, it doesn't need to remain open. We can revive it in the future.

**Comment by karmakaze** [comment]
@jez Thanks for taking the time to explain the situation. I completely understand and agree with the outcome.

I became interested in contributing because I was bumping into some issues, so scratching the itch.

Unrelated to this issue, but since it was suggested I look for another area... One sore spot is re: https://srb.help/7019 . I ran into this as using `T.unsafe` is very unsafe for common Hash that use splats. Could there be anything in that area where I could contribute, perhaps some .rbi's for methods or anything?

_For sure, I'll search the issues and read any existing information on this topic as well._ Thanks again!

**Comment by jez** [comment]
The problem with splats is that if `opts` is typed loosely as `T::Hash[Symbol, T.untyped]`, we don't know whether all the required keyword args are included in `opts` when doing something like

```ruby
foo(**opts)
```

We have two options:

- Be explicit about this and require people to opt-out of type checking by untyping the code
- Being silent, and letting the code pass (possibly erroneously)

Ultimately, the only thing that would truly solve this in any ergonomic sense would be to improve sorbet's support for shape types.

**Comment by karmakaze** [comment]
Oh sorry I wasn't clear. I was bumping more into the single splats rather than double splats:
```
foo(*opts)
```

**Comment by jez** [comment]
ah got it. I agree that is an example that should be able to type check but I don't have any good ideas for how to accomplish that off the top of my head

**Pull request closed without merging**
