### PR TITLE
Split pipeline::package into two calls

### PR DESCRIPTION
**Pull request by jez**
### Motivation

This should be a no-op, but sets us up to be able to run the packager before we
index the rest of the codebase.

In the mean time, I just want to land it to make sure that there are neither
correctness nor performance regressions.

### Test plan

Changed the pipeline test runner to mimic the realmain changes.

### CODE REVIEW

**Comment by jez** [comment]
Current dependencies on/for this PR:
* master
  * **PR #7215** <a href="https://app.graphite.dev/github/pr/sorbet/sorbet/7215" target="_blank">Graphite</a>  👈
    * **PR #7218** <a href="https://app.graphite.dev/github/pr/sorbet/sorbet/7218" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sorbet/sorbet/7215?utm_source=stack-comment).

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_OQA7R5nVd73orr
→ https://go/builds/bui_OQA81tXxyXxLtH
→ https://go/builds/bui_OQA88KIzT7hawh

**Review by ilyailya — CHANGES_REQUESTED** [review]
@jez looks like there are some test failures. Should I review the change now, or you still planning to work on it?

**Comment by jez** [comment]
Still working, sorry!

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_OQrra6aYsD3Fvl
→ https://go/builds/bui_OQrrnF5SSiAGWF
→ https://go/builds/bui_OQrrMmdCKEKT31

**Review by ilyailya — APPROVED** [review]

**Comment by jez** [comment]
This doesn't appear to have any impact on cold-cache performance on Stripe's codebase, so I'm going to go ahead and merge.

**Pull request merged**
