### PR TITLE
Add missing definitions for `Kernel`

### PR DESCRIPTION
**Pull request by Morriar**
No signatures.

### CODE REVIEW

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HOWNhbwGneZnaa

**Comment by Morriar** [comment]
@elliottt sorry, I rebased this one by mistake.

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HOWUZKCLap8Y9U

**Comment by elliottt** [comment]
@Morriar the stripe build passed, but the sorbet CI is failing. Could you take a look at the errors?

**Comment by Morriar** [comment]
@elliottt I fixed the test.

When autocompleting `x.me`, "Pathna*me*" is now also returned in the condidates.

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HOro289DD6jzxK

**Pull request merged**
