### PR TITLE
desugar: Reorder cases by current frequency

### PR DESCRIPTION
**Pull request by jez**
### Test plan

See included automated tests.

### CODE REVIEW

**Review by froydnj — APPROVED** [review]
I was just thinking about this the other day, thank you for doing this!

(We really have more const references than sends in raw ruby files?  Wild.)

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_L3XKkPkiF1NEYc
→ https://go/builds/bui_L3XKJdYP7S9AN2

**Comment by jez** [comment]
> (We really have more const references than sends in raw ruby files? Wild.)

- `A::B::C::D::E.f` is 5 constants and one send
- Stripe's Ruby build system creates a bunch of constant-heavy files in the `build/` folder (for things like the autoloader and subclasses lists)

**Comment by jez** [comment]
This only accounts for a slight speedup (0.5% or so) on a cold cache.

http://go/gist/jez/ec60b8e0c543e9b70eb6dc6dc946d156

**Pull request merged**
