### PR TITLE
Docs: Fix description of `typed: strong`

### PR DESCRIPTION
**Pull request by jaredbeck**
### Motivation

This sentence seems incorrect.

### Test plan

N/A

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Oh, now it makes sense and that is not clear at all in the current text. Maybe we should expand what `impossible to write files with no error` means in that context.

**Comment by jaredbeck** [comment]
> Most Ruby files that actually do interesting things will have errors in # typed: strong.

Updated accordingly, thanks Jake.

**Comment by jez** [comment]
@jaredbeck the linters are failing because prettier complains on this file. Can you either clone and run prettier locally, or reformat the diff to fit within 80 columns manually?

**Comment by jez** [comment]
@jaredbeck I've merged master into your branch (to pick up the fixes to a broken master) and fixed the prettier issues in your PR manually.

I'll merge this when the build passes. Thanks for your PR!

**Pull request merged**
