### PR TITLE
Add intrinsic for `sample` on `TupleType`

### PR DESCRIPTION
**Pull request by jez**
### Motivation

Requested on Slack.

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_M6JagbNNebXOT2
→ https://go/builds/bui_M6JaVW6KI8a2dP

**Review by froydnj — APPROVED** [review]

**Comment by will** [comment]
I think it is incorrect to make the result of sample be not nilable. A 3 tuple doesn't always stay a 3 tuple

https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aa%20%3D%20%25w%5Ba%20b%20c%5D%0Aa.reject!%20%7B%20true%20%7D%0Athis_is_actually_nil%20%3D%20a.sample%0AT.reveal_type%20this_is_actually_nil

```ruby
# typed: strict

a = %w[a b c]
a.reject! { true }
this_is_actually_nil = a.sample
T.reveal_type this_is_actually_nil # Revealed type: String
```

**Comment by jez** [comment]
Yeah, that's a problem with tuples more generally, and is a reason why tuples are still experimental

**Comment by jez** [comment]
The bug you mention already existed before this PR:

https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aa%20%3D%20%25w%5Ba%20b%20c%5D%0Aa.reject!%20%7B%20true%20%7D%0Athis_is_actually_nil%20%3D%20a%5B0%5D%0AT.reveal_type%20this_is_actually_nil

In the future we will have to teach Sorbet how to deal with methods that mutate the type of the method receiver on tuple types.

**Comment by will** [comment]
Ok. I will drop a T.must around a sample I'm doing, since for me I expect it to never reject everything in the first place.

But as for tuples being experimental, I'm not intentionally using them. I'm just making an array and sorbet is deciding to use the experimental feature without my knowledge. I'd be happy for sorbet to think my array is always an array, but I don’t know how.

**Pull request merged**
