### PR TITLE
Even wimpier big lubs test.

### PR DESCRIPTION
**Pull request by jvilk-stripe**
Even wimpier big lubs test.

Let's dilute this test further.

### Motivation

Times out on Mac. I reproduced the timeout locally (occurs when running entire test suite).

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jvilk-stripe** [comment]
In parallel I'm seeing if this would still fail pre-lub change.

**Comment by jvilk-stripe** [comment]
The new file takes 78.61s on my machine pre-lub change.

**Review by elliottt — APPROVED** [review]
👍

**Comment by jez** [comment]
@jvilk-stripe is this test worth keeping?

It's almost never going to fail in CI if we regress it as far as I understand.

I'm also not a fan of introducing artificially slow tests, because then we have to run them in CI and thus our CI is slow.

**Comment by elliottt** [comment]
> @jvilk-stripe is this test worth keeping?
> 
> It's almost never going to fail in CI if we regress it as far as I understand, because it is not failing on Linux.
> 
> I'm also not a fan of introducing artificially slow tests, because then we have to run them in CI and thus our CI is slow.

I think that the timings that @jvilk-stripe posted from before the lubs branch change indicate that it will fail, as it would take 78s to run (bazel will timeout before that).

**Comment by elliottt** [comment]
@jvilk-stripe does this test fail on linux pre-big lubs PR, when it's this watered down?

**Comment by jvilk-stripe** [comment]
>I think that the timings that @jvilk-stripe posted from before the lubs branch change indicate that it will fail, as it would take 78s to run (bazel will timeout before that).

This is correct.

> @jvilk-stripe does this test fail on linux pre-big lubs PR, when it's this watered down?

Let me check. If it doesn't, I'm OK with removing the test.

**Comment by jvilk-stripe** [comment]
Closing in favor of https://github.com/sorbet/sorbet/pull/3430

**Pull request closed without merging**
