### PR TITLE
Use portable debug traps

### PR DESCRIPTION
**Pull request by vinistock**
_This is part of the work for compiling Sorbet on M1 macs_

Use portable debug traps instead of embedded x86 assembly.

### Motivation

The x86 instructions will not compile on ARM64, so we need to use a portable alternative.

### Test plan

Current tests should cover it.

### CODE REVIEW

**Review by jez — APPROVED** [review]

**Comment by vinistock** [comment]
Not sure why the compiler complains about `__builtin_debugtrap()`. I think an alternative is including `signal.h` and using `raise(SIGTRAP)`, but I'm not 100% sure. Thoughts?

**Comment by elliottt** [comment]
> Not sure why the compiler complains about `__builtin_debugtrap()`. I think an alternative is including `signal.h` and using `raise(SIGTRAP)`, but I'm not 100% sure. Thoughts?

This seems like a good solution to me 👍

**Comment by froydnj** [comment]
> Not sure why the compiler complains about `__builtin_debugtrap()`. I think an alternative is including `signal.h` and using `raise(SIGTRAP)`, but I'm not 100% sure. Thoughts?

GCC apparently doesn't support `__builtin_debugtrap`, which is what is being used in CI to compile Ruby (maybe just the GCC version we're using?).  You could try changing it to `__builtin_trap` just for `vm-payload.c`, or you could add processor-specific code to emit the same instructions that Clang would.

**Comment by vinistock** [comment]
Changed only the occurrence in `vm-payload` to use `raise(SIGTRAP)`, which seems to do the trick.

**Review by elliottt — APPROVED** [review]
Thanks!

**Pull request merged**
