### PR TITLE
Reduce packager allocations

### PR DESCRIPTION
**Pull request by elliottt**
While looking at the region of a trace attributed to `findPackages`, @froydnj and I noticed a few things that could be improved with the current implementation:

- Vectors were being copied out of global state, despite the functions that return them returning a constant reference
- std::stringstream was used where a preallocated string would work
- Inserting packages into the packageDB was using `find` and then `[]` to assign, when it could use the single `insert` function that does both.

### Motivation
Performance of stripe-packages.

### Test plan

This shouldn't change any behavior, only improve performance when stripe-packages is enabled.

### CODE REVIEW

**Comment by jez** [comment]
> While looking at the region of a trace

I take this to mean: you're using the web-trace-file output to narrow in on which segment of code to look at, and then using judgement to find these optimizations? or is there some other tool you're using to profile allocations directly?

**Comment by elliottt** [comment]
> > While looking at the region of a trace
> 
> I take this to mean: you're using the web-trace-file output to narrow in on which segment of code to look at, and then using judgement to find these optimizations? or is there some other tool you're using to profile allocations directly?

Exactly: `findPackages` takes a long time to run, and we were curious if there was anything obvious that could be simplified.

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_RLTQOnsbw6MJA4
→ https://go/builds/bui_RLTRcLTMAp9XY5
→ https://go/builds/bui_RLTRzzihWyZPWz

**Comment by elliottt** [comment]
I ran this on stripe's codebase and generated a trace file. This branch cut the time the packager pass was running by about 25%.

**Review by ilyailya — APPROVED** [review]

**Pull request merged**
