### PR TITLE
Add Etc::Group struct members

### PR DESCRIPTION
**Pull request by dduugg**
See https://docs.ruby-lang.org/en/3.3/Etc/Group.html

### CODE REVIEW

**Comment by froydnj** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_PVtXduP6ZCD8Jf
→ https://go/builds/bui_PVtXc9JyJXKX2q
→ https://go/builds/bui_PVtXcT4HRaaPl2

**Comment by dduugg** [comment]
friendly bump @froydnj

**Comment by dduugg** [comment]
friendly bump @neilparikh

**Review by neilparikh — APPROVED** [review]
Whoops, I missed this PR somehow, sorry for the delay!

**Comment by dduugg** [comment]
TY! 🙇

**Pull request merged**
