### PR TITLE
Update faq.md

### PR DESCRIPTION
**Pull request by vaporyhumo**
It's just a typo on the faqs.

### CODE REVIEW

**Comment by elliottt** [comment]
Could you run `tools/scripts/format_website.sh` and commit the results?

**Comment by vaporyhumo** [comment]
Yeah, sure.

**Comment by vaporyhumo** [comment]
Actually my repo stays the same after running it. Is it the same file that should be modified?

**Comment by vaporyhumo** [comment]
Maybe I should do something else beforehand? I just cloned the repo and run the script. The first commit was made via github.

**Comment by elliottt** [comment]
Did you check out your branch after cloning? It's definitely that script that failed: https://buildkite.com/sorbet/sorbet/builds/10595#1f2ad297-474d-42dd-a30c-f5cff400432f/158-180

**Comment by vaporyhumo** [comment]
nvm wrong branch

**Comment by vaporyhumo** [comment]
Should I squash the commits or is it fine that way?

**Comment by elliottt** [comment]
It's fine the way it is -- we always squash merge PRs.

**Comment by vaporyhumo** [comment]
NP, thank you too for making this awesome tool!~

**Pull request merged**
