### PR TITLE
Add `BigDecimal::SIGN_NaN` definition.

### PR DESCRIPTION
**Pull request by bartle-stripe**
### Motivation
Sorbet generates an error if you use this constant.

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by elliottt** [comment]
Could you run `gems/sorbet/test/hidden-method-finder/update_hidden_methods_exp.sh` and commit the results?

**Comment by bartle-stripe** [comment]
PTAL @elliottt 

Is there something that needs to be triggered to re-run tests?

**Comment by elliottt** [comment]
Should be unblocked now, thanks!

**Comment by bartle-stripe** [comment]
I'm not sure where `GMP_VERSION` is coming from, but I've manually removed those additions.

PTAL @elliottt

**Pull request merged**
