### PR TITLE
Preserve BlockArgs after namer

### PR DESCRIPTION
**Pull request by gdritter-stripe**
### Motivation
The namer will process arguments and reconstruct a tree in-place, but we previously were not preserving the block-ness of block args, turning them into positional args. This would manifest if we re-ran the namer over the same tree, something we do in `namer_test.cc`, as the two methods not actually having the same signature.

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by DarkDimius** [comment]
Don't we do the same thing for keyword arg too?

AFAIK this was intentional, to make sure we don't have information duplicated. If method tree has a `symbol` set, it's a source of truth for arguments, rather than the tree itself.

**Comment by DarkDimius** [comment]
AFAIK the only information that's left in three after namer about arguments is if the argument was optional. And it's left only because we need to keep the default value.

**Comment by gdritter-stripe** [comment]
If this is intentional, then the thing that needs to change is this test https://github.com/sorbet/sorbet/blob/master/namer/test/namer_test.cc#L82-L106 which runs the namer on line 93 and then again over the post-namer tree on 103. With the other namer changes I made, this fails because it tries to regenerate arguments from the tree but that tree has scrubbed all the salient argument information from the tree itself. In light of this, I think that test is doing something wrong.

**Comment by gdritter-stripe** [comment]
I've fixed that test in another way, so I'm going to close this one as not the right solution.

**Pull request closed without merging**
