### PR TITLE
Add missing RBI definitions for BigDecimal

### PR DESCRIPTION
**Pull request by Morriar**
### Motivation

Add missing RBI definitions for BigDecimal

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by Morriar** [comment]
Note that some methods in here don't have a signature.

**Comment by jez** [comment]
http://go/builds/bui_HHJe9AxrWLpYX5

**Comment by jez** [comment]
This caught two type errors in Stripe's codebase. Thanks!

I've fixed the errors and will merge this after the fixes to Stripe's codebase have landed.

**Comment by jez** [comment]
Thanks!

**Pull request merged**
