### PR TITLE
Pre-work for #6521

### PR DESCRIPTION
**Pull request by jez**
### Motivation

Something is wrong with #6521. I'm going to try bisecting it.

**Update** as of right now, these are all the okay changes, and the problem is now wholly contained in #6521.

May as well land this.

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_MjDUDlLeS2TcA2
→ https://go/builds/bui_MjDUJrQ0TyJKuR

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_MjENJcrONUqAd1
→ https://go/builds/bui_MjENUJvXnqDwGQ

**Comment by jez** [comment]
Current dependencies on/for this PR:
* master
  * **PR #6534** <a href="https://app.graphite.dev/github/pr/sorbet/sorbet/6534" target="_blank">Graphite</a>  👈
    * **PR #6521** <a href="https://app.graphite.dev/github/pr/sorbet/sorbet/6521" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sorbet/sorbet/6534?utm_source=stack-comment).

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_Mk3fbBeyu1GFYk
→ https://go/builds/bui_Mk3fqjGcTKV5Af

**Review by froydnj — APPROVED** [review]

**Pull request merged**
