### PR TITLE
[WIP][Upgrade] bazel version

### PR DESCRIPTION
**Pull request by grahamjenson**
Upgrading Bazel to 1.2.1. 

### Motivation

This upgrade should allow newer build optimizations and allow other projects to use sorbet.

### Test plan
If the builds work and tests run this should be fine

### CODE REVIEW

**Comment by DarkDimius** [comment]
❤️ Thank you for taking this on!

Heads-up,
we're using the following toolchain that will also need to be upgraded to be compatible with newer bazel.
https://github.com/DarkDimius/bazel-toolchain/tree/dp-srb-now

**Comment by grahamjenson** [comment]
@DarkDimius I just moved it over to the newer version of the forked https://github.com/grailbio/bazel-toolchain/commits/master which has been updated to support bazel version 1.0. 
Will this work, or will I need to upgrade your forked version?

**Comment by elliottt** [comment]
> Will this work, or will I need to upgrade your forked version?

The forked version will need to be updated as well.

**Comment by grahamjenson** [comment]
I have left this PR as we are moving a different way on rules_ruby.

**Pull request closed without merging**
