### PR TITLE
Add -p compilied-files-json

### PR DESCRIPTION
**Pull request by elliottt**
Add the `compiled-files-json` print option, which prints out a json array that contains objects describing the compiled status of each file processed. Example output looks like:

```[{"file":"compiled-false.rb","compiled":"false"},{"file":"compiled-none.rb","compiled":"none"},{"file":"compiled-true.rb","compiled":"true"}]```

And pretty-printed:

```
[
  {
    "file": "compiled-false.rb",
    "compiled": "false"
  },
  {
    "file": "compiled-none.rb",
    "compiled": "none"
  },
  {
    "file": "compiled-true.rb",
    "compiled": "true"
  }
]
```

### Motivation

Collecting stats on the number of files that are compiled.

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by froydnj** [comment]
Can you explain the rationale behind doing it as a `-p` option, rather than specifying a filename to print the json to?

**Comment by elliottt** [comment]
> Can you explain the rationale behind doing it as a `-p` option, rather than specifying a filename to print the json to?

It followed well with existing printing options like symbol-table-json. Since PrintOptions also support writing to a file, I'd be happy to add that support as well.

**Comment by elliottt** [comment]
> > Can you explain the rationale behind doing it as a `-p` option, rather than specifying a filename to print the json to?
> 
> It followed well with existing printing options like symbol-table-json. Since PrintOptions also support writing to a file, I'd be happy to add that support as well.

@froydnj I'm not sure how I missed this, but the printing options support this already: `--print compiled-files-json:out.json` will write the output to `out.json`.

**Comment by froydnj** [comment]
> > > Can you explain the rationale behind doing it as a `-p` option, rather than specifying a filename to print the json to?
> > 
> > 
> > It followed well with existing printing options like symbol-table-json. Since PrintOptions also support writing to a file, I'd be happy to add that support as well.
> 
> @froydnj I'm not sure how I missed this, but the printing options support this already: `--print compiled-files-json:out.json` will write the output to `out.json`.

TIL!

**Review by froydnj — APPROVED** [review]

**Pull request merged**
