### PR TITLE
WIP: handle super in strict files

### PR DESCRIPTION
**Pull request by neilparikh**
### TODO
- [ ] turn off method suggestions for super
- [ ] new error code for ancestors not found

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
nit: let's use NameRef::noName, which is more common in the codebase, and a little more descriptive

Screenshot 2023-08-07 at 2 54 30 PM

**Comment by jez** [comment]
@neil No response expected:

Tomorrow I'm going to review this change as though it were ready for review, just so you can see the comments I would have left, before I go ahead and make those changes for you.

Hopefully the review will be valuable for you. To make it so that you can still see the comments easily when you get back, I'll finish the change in a separate pull request, so that the comments I leave here don't get marked as outdated.

**Comment by jez** [comment]
@neilparikh  No response expected:

Tomorrow I'm going to review this change as though it were ready for review, just so you can see the comments I would have left, before I go ahead and make those changes for you.

Hopefully the review will be valuable for you. To make it so that you can still see the comments easily when you get back, I'll finish the change in a separate pull request, so that the comments I leave here don't get marked as outdated.

**Comment by neilparikh** [comment]
Continued in https://github.com/sorbet/sorbet/pull/7231

**Pull request closed without merging**
