### PR TITLE
fix master only documentation

### PR DESCRIPTION
**Pull request by ptarjan**
I think you accidentally removed this in 7bf1a754f8e61168f29da781ebdb32b5b98452c9

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by elliottt** [comment]
This was removed intentionally to ensure that the tests for `@ruby_2_4_3` (which only currently run on mac) were continuing to be tested. Getting `@ruby_2_4_3` building on linux would mean that we could put this test back to master only.

**Comment by ptarjan** [comment]
@elliottt that's unfortunate. Ok, I fixed the documentation then instead.

**Comment by ptarjan** [comment]
Also, why couldn't you just run that bazel test target then in a new job?

**Comment by elliottt** [comment]
> Also, why couldn't you just run that bazel test target then in a new job?

@DarkDimius was concerned that we would get less parallelism from a new job than we would from merging this test in with an existing one. That might have been assuming that we were able to target linux, though. I'm happy to pull this out into a temporary separate job if it's causing builds to take too long in the short-term.

**Comment by ptarjan** [comment]
Thanks for the explanation. I don't know if it is causing issues. Please keep an eye on if this is now the long pole during testing.

**Comment by elliottt** [comment]
@ptarjan are you okay with closing this PR?

**Comment by ptarjan** [comment]
@elliottt I'd like to land it in its current form. Do you still want it to say `(master only)`?

**Comment by elliottt** [comment]
Removing `(master only)` is a good change.

**Pull request merged**
