### PR TITLE
Expand `OpAsgn` when suggesting `T.must`

### PR DESCRIPTION
**Pull request by jez**
### Motivation

Fixes <https://github.com/sorbet/sorbet/issues/3370>

This will also help unblock certain portions of the (eventual) migration to fix
shape types, because this is a common class of error that appears when shape
type are improved to actually check accessors (instead of being completely
untyped).

### Test plan

Tests show before/after

### CODE REVIEW

**Review by elliottt — APPROVED** [review]
Is it worth adding a test for something like the following?
```
x, y = [1, T.let(nil, T.nilable(String))]
y.split
```

**Comment by jez** [comment]
Hm, we definitely could, but that is completely unrelated to these changes, as it doesn't have anything to do with OpAsgn, right?

**Comment by jez** [comment]
(I double checked, your test case passes before the changes made in this PR.)

**Comment by elliottt** [comment]
> Hm, we definitely could, but that is completely unrelated to these changes, as it doesn't have anything to do with OpAsgn, right?

Good point, I was confusing this with assignment in general and remembered having trouble with `T.must` autocorrects and the destructured assignment in the past.

**Pull request merged**
