### PR TITLE
Decrease suggest-typed attempts from 100 to 50.

### PR DESCRIPTION
**Pull request by connorshea**
The 100 attempts was originally set in https://github.com/sorbet/sorbet/commit/385ccb7be8c8fbb281670b9eedc4c890785d349d.

### Motivation
It's probably pretty unlikely that the sigils will converge after 100 attempts if they haven't after 50. This reaches the failure state a bit faster so the user isn't stuck waiting for as long. It takes around 10 minutes (for me, at least) to hit the 100 attempts mark. The length of my wait might have been because of the library that was causing the problem, or something else. I'm not entirely sure.

### CODE REVIEW

**Comment by DarkDimius** [comment]
@connorshea , I believe this number was obtained through one of our tests for a rails codebase(was it gitlab? I'm unsure).

Would you be up to convert this into a user prompt to ask if they want to continue?

**Comment by connorshea** [comment]
@DarkDimius that'd make sense then, yeah sure :) Would you be alright if I added a progress message every 10 attempts as well? Right now it doesn't output anything while you wait.

**Comment by DarkDimius** [comment]
>  Would you be alright if I added a progress message every 10 attempts as well?

that would be great!
Could you send it as a separate followup please?

Thank you!

**Comment by connorshea** [comment]
I've updated the suggest-typed file to ask the user if they want to continue after 50 attempts, the code was mostly lifted from `srb-rbi`. I'm not sure how exactly I should test this, though. Is there an easy way to generate a gem I can use locally with bazel?

**Comment by DarkDimius** [comment]
> Is there an easy way to generate a gem I can use locally with bazel?

https://github.com/sorbet/sorbet/blob/master/.buildkite/test-static-sanitized.sh#L27-L28 is the invocation that we use in CI, it builds the gems and tests them with bazel

**Comment by DarkDimius** [comment]
@connorshea would it be possible for you to rebase and run `./tools/scripts/update_exp_files.sh`?
Unfortunately I can't push to your branch to do that for you

**Comment by connorshea** [comment]
@DarkDimius Weird, I definitely have 'Allow edits from maintainers' checked for the PR.

I can regenerate the expectations, but I don't think that should actually be necessary for this PR. Do you mean #1265?

**Comment by DarkDimius** [comment]
> I definitely have 'Allow edits from maintainers' checked for the PR.

Interesting. Either I'm doing something wrong, or this option only allows edits via github UI.
I wasn't able to push to your repo via command line.

**Comment by connorshea** [comment]
I'm guessing you can push 'normal' commits, it just doesn't allow force pushes.

**Comment by DarkDimius** [comment]
Thank you!

**Pull request merged**
