### PR TITLE
Add RBI for stdlib/rubygems

### PR DESCRIPTION
**Pull request by Morriar**
No signature.

### CODE REVIEW

**Comment by jez** [comment]
Testing on Stripe's codebase:

https://go/builds/bui_HJXib5LpKKwIJK

**Comment by Morriar** [comment]
^ fixed tests

**Comment by jez** [comment]
https://go/builds/bui_HMb0XK4fHk7ufl

**Comment by jez** [comment]
This one is causing a few problems because we already have `rbi/stdlib/gem.rbi` in Sorbet (should probably be called `rubygems.rbi`, and also there are are some conflicting things in Stripe's autogenerated `rubygems.rbi`.

Do you mind if I take over rubygems.rbi with a branch of my own? I think it might solve most of the same problems and be less back and forth.

**Comment by Morriar** [comment]
@jez please do ❤️

**Comment by jez** [comment]
Closing in favor of #3102

**Pull request closed without merging**
