### PR TITLE
Revert "Make the canonical loc of a symbol the strictest"

### PR DESCRIPTION
**Pull request by elliottt**
Reverts sorbet/sorbet#2873

### CODE REVIEW

**Comment by DarkDimius** [comment]
Did we understand why this caused regression?

**Comment by elliottt** [comment]
> Did we understand why this caused regression?

My best guess is that it's the loop in `bestNonRBIFile`.

**Comment by jez** [comment]
From perf:

```
+   70.78%    70.55%  typeche  sorbet              [.] sorbet::definition_validator::bestNonRBIFile
```

my guess: the loop in bestNonRBIFile loops over all locs for a class
<root> has something like 65,000 locs
every file has a <root> constant reference
there are 65,000 files

**Comment by jez** [comment]
From perf:

```
+   70.78%    70.55%  typeche  sorbet              [.] sorbet::definition_validator::bestNonRBIFile
```

my guess: the loop in bestNonRBIFile loops over all locs for a class
<root> has something like O(num files) locs
every file has a <root> constant reference
which makes this accidentally quadratic

**Comment by elliottt** [comment]
Stripe build: https://go/builds/bui_H9BHwSLfo8H7qN

**Pull request merged**
