### PR TITLE
Mark sorbet_i_objIsKindOf as const

### PR DESCRIPTION
**Pull request by elliottt**
Remove `sorbet_isa` in favor of a direct call to `sorbet_i_objIsKindOf`, and mark `sorbet_i_objIsKindOf` as `const`. Also change the return type of `sorbet_i_objIsKindOf` to `_Bool`, matching the other type testing intrinsics.

### Motivation

Cleaning up generated code, coalescing calls to `sorbet_i_objIsKindOf` when possible.

### Test plan

See included automated tests.

### CODE REVIEW

**Review by jez — APPROVED** [review]
Is it intentional that there are no tests? Would a filecheck test be possible?

**Comment by elliottt** [comment]
> Is it intentional that there are no tests? Would a filecheck test be possible?

It was intentional, but I think you're right that it would be nice to have a test to verify the coalescing.

**Comment by elliottt** [comment]
OK, I had trouble writing a test to verify the behavior I expected because the function that I removed, `sorbet_isa`, is marked const and was coalescing before inlining to a `sorbet_i_objIsKindOf` call. The result is that this PR should basically be a no-op, but will leave the door open to `sorbet_isa` calls coalescing later than `sorbet_isa` would have.

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_KhSU1LCyIOvaih
→ https://go/builds/bui_KhSUyy3B0YHCpV

**Pull request merged**
