### PR TITLE
auto-assign to oncall

### PR DESCRIPTION
**Pull request by ptarjan**
Today PR pick someone from our normal rotation which is a bit interuptive. What do you think about having an alias that gets assigned all ticket? This will force us to internally pick the round-robin assigner by hand which I don't love but I don't see another way.

I used the word oncall since that is more publicly known than onrun.

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by elliottt** [comment]
Is this just for PRs from non-members, or all PRs that have no reviewer assigned?

**Comment by ptarjan** [comment]
This commit is for everyone. I'd love if we could bifricate but I don't see how in CODEOWNERS

**Comment by DarkDimius** [comment]
I've added automation to this via https://pullreminders.com/installs/46383129/assigner/teams/1340
👍

**Comment by ptarjan** [comment]
@DarkDimius do we then want the rotation that it points at to be empty and have it proxy to a real one so that if we internally already pick a reviewer it won't do anything? (like you do with the other team)?

**Comment by ptarjan** [comment]
I updated https://pullreminders.com/installs/46383129/assigner/teams/1340 to use a proxy team so hopefully it won't assign someone if someone else is already assigned

**Pull request merged**
