### PR TITLE
Try removing the minitest DSL

### PR DESCRIPTION
**Pull request by jez**
### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_LdqtqaDVC97TBr
→ https://go/builds/bui_LdqtV5KugHmtoV

**Comment by Morriar** [comment]
This rewriter is very useful for us. Why is it considered for removal?

**Comment by jez** [comment]
We think we might be able to replace it with T.proc.bind(T.attached_class).void on the ‘it’ method, which would let code like `[true, false].each {it ‘’ {}}` typecheck without needing to use test_each. Nathan was looking further into it

**Comment by froydnj** [comment]
> We think we might be able to replace it with `T.proc.bind(T.attached_class).void` on the ‘it’ method, which would let code like `[true, false].each {it ‘’ {}}` typecheck without needing to use test_each. Nathan was looking further into it

Despite the coolness of `T.proc.bind(T.{self_type,attached_class})` is, it's not sufficient for modeling minitest, and the minitest rewriter, despite all its problems, is a much better option.

**Pull request closed without merging**
