### PR TITLE
Delete SelfNew

### PR DESCRIPTION
**Pull request by jez**
### Motivation

The recent changes to use `T.attached_class` as the return type of `Class.new` means that we don't actually have to do any extra work to compute the return type of `new`.

In the beginning of Sorbet, the `Class_new` intrinsic was responsible for looking at the type of the receiver, using the type of the receiver to compute an instance type, and setting that instance type as the result of `new`. We can delete that code now.

What that means is that Sorbet will be smart enough to know that _inside_ a singleton class, `self.new` can have the type `T.attached_class`. Outside a singleton class, Sorbet will know that `Child.new` will have type `Child`. This works because of how Sorbet's `resultTypeAsSeenFrom' helper works, which instantiates a generic type member from the perspective of either within a method or at the call site of a method.

The `SelfNew` intrinsic was originally conceived as a hack, to allow people to write strongly-typed methods that called `new` and were annotated as returning `T.attached_class`. Before, `self.new` inside `Parent.make` would have type `Parent`:

```ruby
class Parent
  def self.make
    new
  end
end
```

so we added the `self.new` intrinsic to work around it.

No more hacks!

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
Current dependencies on/for this PR:
* master
  * **PR #6970** <a href="https://app.graphite.dev/github/pr/sorbet/sorbet/6970" target="_blank">Graphite</a> 
    * **PR #6781** <a href="https://app.graphite.dev/github/pr/sorbet/sorbet/6781" target="_blank">Graphite</a> 
      * **PR #6978** <a href="https://app.graphite.dev/github/pr/sorbet/sorbet/6978" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sorbet/sorbet/6978?utm_source=stack-comment).

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_NskrVmo6mqwzgI
→ https://go/builds/bui_NskrCumo96UtrN
→ https://go/builds/bui_Nskr6Ox3sI10dD

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_NsmZzFh37tuI0L
→ https://go/builds/bui_NsmZfIcIazUsIb
→ https://go/builds/bui_NsmZ5sbnx21OgR

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_Nsno01zUODPU1m
→ https://go/builds/bui_NsnofpAs3Cduhv
→ https://go/builds/bui_Nsno3YnyRTeNm0

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_NudWdWYaV7R0i4
→ https://go/builds/bui_NudWJHb3KXtbVQ
→ https://go/builds/bui_NudWinF2fRPs37

**Review by ilyailya — APPROVED** [review]

**Pull request merged**
