### PR TITLE
Add monkey-patched JSON Generator modules

### PR DESCRIPTION
**Pull request by dduugg**
```
$ irb
irb(main):001:0> Array.ancestors
=> [Array, Enumerable, Object, PP::ObjectMixin, Kernel, BasicObject]
irb(main):002:0> Hash.ancestors
=> [Hash, Enumerable, Object, PP::ObjectMixin, Kernel, BasicObject]
irb(main):003:0> require 'json'
=> true
irb(main):004:0> Array.ancestors
=> [Array, JSON::Ext::Generator::GeneratorMethods::Array, Enumerable, Object, JSON::Ext::Generator::GeneratorMethods::Object, PP::ObjectMixin, Kernel, BasicObject]
irb(main):005:0> Hash.ancestors
=> [Hash, JSON::Ext::Generator::GeneratorMethods::Hash, Enumerable, Object, JSON::Ext::Generator::GeneratorMethods::Object, PP::ObjectMixin, Kernel, BasicObject]
```

### CODE REVIEW

**Comment by neilparikh** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_PX45cdZGyBHeQ0
→ https://go/builds/bui_PX45SDVDfIyaeg
→ https://go/builds/bui_PX45AbZRmWVSsN

**Review by jez — COMMENTED** [review]
Can you go one step further and

- move all of [these](https://github.com/sorbet/sorbet/blob/master/test/testdata/rbi/json.rb#L3-L37) into this RBI file
- delete them from that test, because they'll no longer be required?

**Comment by dduugg** [comment]
@jez done, PTAL

**Review by jez — APPROVED** [review]

**Comment by dduugg** [comment]
@jez could i possibly trouble you or another maintainer to run `tools/scripts/update_testdata_exp.sh` and commit the results, per suggestion in 
`:linux: test-static-sanitized.sh` logs? I'm getting `FAILED: Build did NOT complete successfully`, seems the most expedient path may be to have someone with a functional build to initiate this.

**Pull request merged**
