### PR TITLE
Add missing definitions in stdlib/net

### PR DESCRIPTION
**Pull request by Morriar**
No signatures.

### CODE REVIEW

**Comment by jez** [comment]
Testing on Stripe's codebase:

http://go/builds/bui_HJXfCFdsFhFyse

**Comment by Morriar** [comment]
^ fixed tests

**Comment by jez** [comment]
@Morriar I included most of these in #3109, so I think i'm going to close this unless you had any opinions otherwise.

**Comment by Morriar** [comment]
Thanks! Closing.

**Pull request closed without merging**
