### PR TITLE
Fix crash in `textDocument/typeDefinition`

### PR DESCRIPTION
**Pull request by jez**
### Motivation

I noticed this showing up in some crash logs at Stripe.

### Test plan

See included automated tests.

Some of the cases I couldn't find test cases for. I've implemented them so that
they won't crash anymore, but it would be nice to have tests for them.

### CODE REVIEW

**Review by froydnj — APPROVED** [review]
I am willing to believe that this is better, but it is not clear to me why this fixes crashes.  Does some later part of the code believe that certain types must have locations returned by this query?  Returning no locations for everything that's not handled by the `typecase`, as is currently done, seems reasonable...but apparently that's not the case?

**Comment by jez** [comment]
> I am willing to believe that this is better, but it is not clear to me why this fixes crashes. Does some later part of the code believe that certain types must have locations returned by this query? Returning no locations for everything that's not handled by the `typecase`, as is currently done, seems reasonable...but apparently that's not the case?

idk if this was always the case or if this was only the behavior implemented once we started using `TypePtr`, but it looks like the default case of a `typecase` on `TypePtr` throws. This is the behavior of the test added here on master:

image

**Comment by jez** [comment]
> idk if this was always the case

It looks like that behavior predates john's TypePtr changes.

**Comment by froydnj** [comment]
Ah right.  Sure would be nice to get a static error for that.

**Pull request merged**
