### PR TITLE
Add a version check for sorbet-typed.

### PR DESCRIPTION
**Pull request by connorshea**
### Motivation

This can't be merged until https://github.com/sorbet/sorbet-typed/pull/221 is.

This adds a check in sorbet-typed that looks at the `.sorbet-typed.yml` file after cloning sorbet-typed, then checks to make sure the version is supported by the current version of Sorbet.

The reason I want to add this now is so that we'll raise an error for the user once sorbet-typed is updated to v2 in the future, rather than just failing silently or with an error about invalid version strings.

For example, this is what it looks like if you try to run `srb rbi sorbet-typed` with sorbet when sorbet-typed is set to version 2 and sorbet only supports v1:

```
Connors-MacBook-Pro:vglist connorshea$ bundle exec srb rbi sorbet-typed 
Running command: sorbet-typed
Generating: sorbet/rbi/sorbet-typed/
Traceback (most recent call last):
	3: from /Users/connorshea/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5365/bin/srb-rbi:237:in `<main>'
	2: from /Users/connorshea/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5365/bin/srb-rbi:224:in `main'
	1: from /Users/connorshea/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5365/bin/srb-rbi:232:in `block in make_step'
/Users/connorshea/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5365/lib/fetch-rbis.rb:153:in `main': Incompatible sorbet-typed version. Please upgrade Sorbet to use the latest signatures from sorbet-typed. (RuntimeError)
```

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by connorshea** [comment]
The PR in sorbet-typed needs to be merged before this'll pass, I think?

**Comment by elliottt** [comment]
@connorshea Is this branch still active? I noticed that https://github.com/sorbet/sorbet-typed/pull/221 is still open, does that need to be merged before this can proceed?

**Comment by connorshea** [comment]
@elliottt yes and yes

**Comment by connorshea** [comment]
@jez yeah I talked with @elliottt about how we'd want to do it w/ the sorbet-typed repo being pulled down in zipped form, but it'd require writing C++ code and I'm allergic :P I honestly think this solution is better, though it's not without downsides. Your call on whether we should close it or not.

**Comment by elliottt** [comment]
I think we'd like to go with the zip file approach, as there are other things that we can do with that once it's landed.

**Pull request closed without merging**
